### ISSUE TITLE
Broken Link For Clay

### ISSUE THREAD

**Issue by JHaugh4** [jaspervdj/hakyll#1005]
I was reading through this page: https://jaspervdj.be/hakyll/tutorials/using-clay-with-hakyll.html and found that the link to Clay is broken. Currently the link points to https://sebastiaanvisser.github.com/clay/ when it should point to https://github.com/sebastiaanvisser/clay.

**Comment by Minoru** [comment]
Thank you! The link on the site will get updated the next time @jaspervdj deploys the site.
