### ISSUE TITLE
`nocite` citations

### ISSUE THREAD

**Issue by KMIJPH** [jaspervdj/hakyll#1029]
Hi,

I've been trying to get nocite citations to work.
e.g
```markdown
---
nocite: |
  @item1, @item2
---
```

Normal inline citations (e.g `[@item1]`) work fine. When converting the markdown file to pdf via pandoc it works fine aswell. The built html version of the file does not contain any of the `nocite` citations though.. I use the standard `pandocBiblioCompiler` provided by hakyll.

**Comment by chungyc** [comment]
Hakyll metadata is not Pandoc metadata.  You have to specify the Pandoc YAML metadata block separately.

For example, see https://github.com/chungyc/site-personal/blob/main/site/publications/index.markdown?plain=1.

**Comment by KMIJPH** [comment]
Ah I didn't know about that, however that doesn't change the fact that (even when specifying a separate block) `nocite` citations do not work for me in Hakyll.

**Comment by KMIJPH** [comment]
Nevermind, I got it working somehow. Thank you!
