### ISSUE TITLE
order of fields in `defaultContext`

### ISSUE THREAD

**Issue by tanyabouman** [jaspervdj/hakyll#1030]
The [`defaultContext`](https://hackage.haskell.org/package/hakyll-4.16.2.0/docs/Hakyll-Web-Template-Context.html#v:defaultContext) makes several fields available in addition to the metadata fields.  These extra fields are `path`, `url`, `title`, and `body`.  The `body` field is always its default definition, but the others can be replaced by the metadata fields of the same name.

Replacing the default `title`  makes sense, and the [example site](https://github.com/jaspervdj/hakyll/blob/030a5fe4bd749798509830bc0eae8cfb87941e7e/web/about.markdown?plain=1#L2) does that.  However, I don't know any use cases for changing the value of `path` or `url`, and I can easily imagine that accidentally replacing their value could cause broken links.

Would it be an improvement to change the order of the fields in `defaultContext` so that `path` and `url` are not replaceable in the metadata?

**Comment by Minoru** [comment]
I don't know offhand how these fields are used internally, so can't comment on how dangerous it is to change them.

However, I often find that something that *can* be done *is* done by someone, so taking it away breaks their setup. For Hakyll, I sometimes search for "site.hs" on GitHub (thus identifying Hakyll users), and then grep those repos for the bit I'm interested in (something like "^path: " in this case). I'm suggesting you do that to see if someone is (ab)using these meta-fields currently.

**Comment by chungyc** [comment]
If one does not want the URL to be the straightforward path-based URL, e.g., if one wants, then changing the `url` field makes sense.  For example, see https://chungyc.org/article/technical/website/extensionless#directory-urls.

I don't know of any good reason to change the `path` field, but neither do I know of a good reason to prevent changing it.

[clean URLs]: https://www.hacksplaining.com/glossary/clean-urls

**Comment by tanyabouman** [comment]
Thanks for the information!  I'll close the issue because the current state seems good.
