### ISSUE TITLE
Spurious underscores in Makefile syntax highlighting

### ISSUE THREAD

**Issue by jstolarek** [jaspervdj/hakyll#1032]
I updated Hakyll to version 4.16.2.0 and noticed a questionable change in syntax highlighting. Consider this snippet of a Makefile:

```
```Makefile
all:
       git add .
       git commit -m "Local changes (via Makefile)" || exit 0

.PHONY: all
\```
```

This is how it used to render:

![before](https://github.com/jaspervdj/hakyll/assets/1597921/f14df5c7-0282-41db-bbdd-96ac98369b37)

vs how it renders now:

![after](https://github.com/jaspervdj/hakyll/assets/1597921/1fd54ee5-6951-4af8-a581-40624d494741)

Note the extra leading underscores. Generated HTML before:

```
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>       git add .</span>
```

and after:

```
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="er">       </span>git add .</span>
```

**Comment by Minoru** [comment]
Hakyll relies on Pandoc for syntax highlighting, which in turn relies on https://hackage.haskell.org/package/skylighting. Most likely skylighting and/or pandoc got updated when updating Hakyll, breaking the resulting HTML. Please report the problem to one of those projects instead.
