### ISSUE TITLE
Markdown list is not converted to HTML list

### ISSUE THREAD

**Issue by UnlimitedCookies** [jaspervdj/hakyll#1051]
A list with dashes `-` is just plainly being inserted into the final HTML document without first being to a HTML list converted; resulting in a mingled document.

Something like
```md
- Firstly
- Secondly
- Thirdly
```
is displayed as
```
- Firstly - Secondly - Thirdly
```
while e. g. markdown links are converted totally fine.

I'm on version `4.16.1.0`.
The corresponding route is
```hs
    match "posts/*" $ do
        route $ setExtension "html"
        compile $ pandocCompiler
            >>= saveSnapshot "content"
            >>= loadAndApplyTemplate "templates/post.html"    postCtx
            >>= saveSnapshot "feed"
            >>= loadAndApplyTemplate "templates/default.html" postCtx
            >>= relativizeUrls
```

**Comment by LaurentRDC** [comment]
Hmm that is curious. In the [Markdown spec](https://daringfireball.net/projects/markdown/syntax#list), lists items can start with `-`. 
Can you provide a Markdown file example so I can try it locally?

**Comment by UnlimitedCookies** [comment]
Sorry for the delayed response. I probably should've provided an example right away to preemptively hint towards what the root cause might be.
It seems we were able to solve the issue by adding an empty line.  Going from 
```md
Inhalte:
- lokales Arbeiten (init, commit, log, checkout) und Speichermodell von Git-Repositories
- manage remote repositories, Branches und Merging
- bei verbleibender Zeit: Advanced Git (mögliche Inhalte sind: searching History, rewriting History, Hooks, typischer Git-Workflow in OpenSource-Projekten)
```
to

```md
Inhalte:

- lokales Arbeiten (init, commit, log, checkout) und Speichermodell von Git-Repositories
- manage remote repositories, Branches und Merging
- bei verbleibender Zeit: Advanced Git (mögliche Inhalte sind: searching History, rewriting History, Hooks, typischer Git-Workflow in OpenSource-Projekten)
```
