### ISSUE TITLE
`match` doesn't seem to work on directories with names starting with `.`

### ISSUE THREAD

**Issue by vaibhavsagar** [jaspervdj/hakyll#1055]
I'm trying to verify my domain for Bluesky, which involves creating a file at `<domain>/.well-known/atproto-did`. Unfortunately it seems like Hakyll doesn't match correctly on directories starting with `.`. For example, I would expect code like this:

```haskell
    match "extra/**" $ do
        route idRoute
        compile copyFileCompiler
```

To work on files at both `extra/regular/foo` and `extra/.dotted/bar`, but it only seems to match on the former while ignoring the latter. I have a small reproducer [here](https://github.com/vaibhavsagar/hakyll-bug). Is this a Hakyll bug or am I doing something wrong?

**Comment by chungyc** [comment]
If you want to match on files or directories starting with a dot, you have to tell Hakyll not to ignore them.

See:
* `ignoreFile` in [`Hakyll.Core.Configuration`](https://hackage.haskell.org/package/hakyll-4.16.3.0/docs/Hakyll-Core-Configuration.html#t:Configuration)
* [`Hakyll.Main.hakyllWith`](https://hackage.haskell.org/package/hakyll-4.16.3.0/docs/Hakyll-Main.html#v:hakyllWith)

**Comment by vaibhavsagar** [comment]
Thanks for pointing that out! I'm not sure that's what's happening here though:

```haskell
ghci> import Hakyll
ghci> shouldIgnoreFile defaultConfiguration "extras/.well-known/atproto-did"
False
ghci> shouldIgnoreFile defaultConfiguration ".well-known/atproto-did"
False
```

**Comment by vaibhavsagar** [comment]
Okay, I updated my configuration with e.g. `ignoreFile = const False` to test this out and indeed that worked. I'm still confused why `shouldIgnoreFile` is giving me an inconsistent result but that's a separate issue.

**Comment by vaibhavsagar** [comment]
I see, thanks for clarifying!

**Comment by jaspervdj** [comment]
FWIW I like saving these files without the `.` in the source of the website so they show up using `ls` and similar.  I then `route` these to files starting with `.`.

**Comment by vaibhavsagar** [comment]
Thanks, that's [what I ended up doing](https://github.com/vaibhavsagar/website/commit/e4f0708408f1340c4c3f2930c6747b0df6b21bdf) too!
