### ISSUE TITLE
"commitBuffer: invalid argument (invalid character)" error when a document contains three dots 

### ISSUE THREAD

**Issue by SiegfriedEhret** [jaspervdj/hakyll#109]
I've added three dots "..." in one of the markdown file from the hakyll-init generated file.
I am getting the following error : 
site: _site/posts/2012-08-12-spqr.html: commitBuffer: invalid argument (invalid character)

It may be related to the fact that pandoc renders "..." as an ellipsis, which may not be recognized by the html builder or something (the html ends at the last character before the dots.).

Thanks !

**Comment by nurpax** [comment]
Btw, seems like en_US locale on Windows 7 and 10 also have this problem.  Would it make sense to default to using this work-around that's mentioned in the FAQ:

```
import qualified GHC.IO.Encoding as E

main :: IO ()
main = do
    E.setLocaleEncoding E.utf8
    hakyll $ do
        ...
```
