### ISSUE TITLE
Implement live-reload for preview mode

### ISSUE THREAD

**Issue by meiersi** [jaspervdj/hakyll#140]
A recent trend for web development is to use live-reload to get rid of the need to refresh the browser by yourself after changing the source files. The implementations work by injecting a piece of JavaScript into the page, which then connects to your preview server and forces a reload if told so. One implementation can be found here: https://github.com/gruntjs/grunt-contrib-livereload.

It should be rather simple to adapt https://github.com/gruntjs/grunt-contrib-livereload to be used in the preview mode of Hakyll.

**Comment by benkolera** [comment]
For anyone that comes along here later. The easiest way that I found was just to reuse the existing nodejs library. It's easy if you already have npm. I wrote about it here: http://benkolera.com/posts/2015-09-14-hakyll_livereload.html

Given that most web dev people tend to have nodejs around for building web stuff and the live reload server is super simple and works, I don't see an intense need to build something into site watch that implemented the LiveReload protocol or anything like that.

Could be documented on the hakyll wiki, though. I'm happy to submit a PR with my docs if that seems like it'd be useful to someone else! :smile:

**Comment by jaspervdj** [comment]
That's a nice and simple solution @benkolera! Feel free to send a PR which adds a tutorial to the Hakyll website.

**Comment by Wizek** [comment]
Nice idea about LiveRealod! Webarchive link for the 404-ing page: 

https://web.archive.org/web/20160414044810/http://benkolera.com/posts/2015-09-14-hakyll_livereload.html

**Comment by haoyun** [comment]
Recently I found live-reload is really useful when building a website, and realized that Hakyll watchserver does not have this great feature. I tried to search the internet and found out this old issue. Besides the above mentioned ideas or solutions, I also found 
* https://www.blaenkdenum.com/posts/live-editing-with-hakyll/
* https://github.com/iand675/live-reload
I started to try to implement it following the ideas above, but finally I found a much simpler solution:
* http://livejs.com/

Just include a JS then problem is (kind of) solved.
Hope this will help other people.

**Comment by manveru** [comment]
Little script for people still looking for a one-liner to recompile the site and clean/watch. This works well combined with the livejs script. The watching is done using http://entrproject.org but you could probably also use https://github.com/watchexec/watchexec

```bash
echo site.hs | entr -n -s 'ghc --make site.hs && ( echo site | entr -n -r -s "./site clean && ./site watch" )'
```
