### ISSUE TITLE
Allow a global metadata file

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/hakyll#152]
Some people prefer putting all of the important metadata in a single file instead of splitting it out. It would be nice if we could either have a "global" or per-directory metadata file. The format should be close to the current format, so probably something like:

    --- foo/bar.markdown
    title: bar
    author: Jasper

    --- foo/qux.rst
    title: jiggles
    author: Jimmy

**Comment by rasendubi** [comment]
@jaspervdj see https://github.com/jaspervdj/hakyll/issues/152#issuecomment-60727025
