### ISSUE TITLE
Expand patterns to work like globs

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/hakyll#18]
I want to expand patterns so glob-like behavior is possible, e.g.:

```
posts/*.jpg
```

**Comment by cdupont** [comment]
It seems that glob in Hakyll are missing some features:
http://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm

In particular curly braces would be useful, to do things like:
    
    match ("blog/posts/**/{*.md,*.lhs}"

**Comment by jaspervdj** [comment]
That's a good idea which I would like to implement.

In the meanwhile, you can use this workaround:

    match ("blog/posts/**/*.md" .||. "blog/posts/**/*.lhs")

Peace,
Jasper
