### ISSUE TITLE
YAML metadata?

### ISSUE THREAD

**Issue by thejohnfreeman** [jaspervdj/hakyll#225]
The metadata supported is not complete YAML. It does not handle lists spanning multiple lines:

```
entries:
- one
- two
- three
```

The error:

```
unexpected "\n"
expecting space followed by metadata for: entries
```

I got the feeling the metadata parser is something custom written for Hakyll. Would it be possible to just use a general YAML parser?

In my particular case, I have about 7 entries, each with multiple fields, that I use to conveniently generate a portion of my page. It's going to look ugly and unmaintainable if consolidated to a single line.

**Comment by FranklinChen** [comment]
I just ran across this incompletely YAML support also, when attempting to start migrating an Octopress-based site to Hakyll.

**Comment by jmatsushita** [comment]
+1 for this. Trying to migrate from metalsmith with YAML frontmatters as well!

**Comment by gpampara** [comment]
+1 Just hit this issue as well. Would be great to get this corrected

**Comment by vjeranc** [comment]
Would fixing this enable easier references (without bib and cls files) using YAML metadata as described [here](http://pandoc.org/README.html#citations)?

**Comment by hazybluedot** [comment]
+1 again, just ran into this trying to port my blog over from nanoc!

**Comment by justinmanley** [comment]
+1 Full YAML front-matter support would be great!

**Comment by jaspervdj** [comment]
Hakyll 0.8.0.0 turns `Metadata` into a YAML object.

**Comment by thejohnfreeman** [comment]
Perfect timing! Just last week I returned to Hakyll after more studiously learning Haskell over the previous months, with the intention of addressing this issue.

**Comment by beerendlauwers** [comment]
Stellar. This is a long-standing issue that made Hakyll a hard sell to some clients and managers.
