### ISSUE TITLE
How do I create a custom metadata list field?

### ISSUE THREAD

**Issue by fhaust** [jaspervdj/hakyll#263]
How would I create a new `listField` that is filled with content from a metadata field? Eg:

    ---
    author: me
    images: foo.jpg, bar.jpg, baz.jpg
    ---

I am trying to fill a gallery on a post page with images. I guess that's the simplest way to do that right?

**Comment by rasendubi** [comment]
@fhaust does that help you? Can the issue be closed?

**Comment by fhaust** [comment]
Wow... Eh... To be honest I don't remember ;-)
Am 04.02.2016 7:26 nachm. schrieb "Alexey Shmalko" <notifications@github.com

**Comment by rasendubi** [comment]
It's expected -- almost two years have passed now. I believe the issue can be safely closed.

/cc @jaspervdj

**Comment by fhaust** [comment]
Yep... Just close it ;-)
Am 04.02.2016 8:24 nachm. schrieb "Alexey Shmalko" <notifications@github.com
