### ISSUE TITLE
Feature request: Build elm-files

### ISSUE THREAD

**Issue by alexander-b** [jaspervdj/hakyll#272]
It would be nice to be able to build Elm[0] files in Hakyll.
Presently, I build them outside of Hakyll using a build.sh script.

Someone started this here:
  <https://github.com/maxsnew/hakyll-elm>.

[0]  <http://elm-lang.org/>

**Comment by jaspervdj** [comment]
You can use `unixFilter` or `system` to build a custom compiler.
