### ISSUE TITLE
hakyll templates expand within html comments

### ISSUE THREAD

**Issue by mikeizbicki** [jaspervdj/hakyll#278]
In the example `index.html` file, if we comment the line partial include line:

```
<!--$partial("templates/post-list.html")$-->
```

Then go into the `site.hs` file and comment the line that adds `posts` to the context:

```
--        listField "posts" postCtx (return posts) `mappend`
```

We get an error when we run `./site build`.  Hakyll is still expanding the code within the html comments even though this will never get displayed.

I'm working through the tutorial examples right now, and I assumed this would not happen, and it took me a while to figure out why I was getting these strange error messages.

**Comment by karlicoss** [comment]
I came up to using something like
```
$if(comment)$
arbitrary comments here
$endif$
```
works well enough. It's still resulting in empty line emitted, but that's good enough for me
