### ISSUE TITLE
Command watch seems to be broken

### ISSUE THREAD

**Issue by kpy3** [jaspervdj/hakyll#298]
Just updated to hakyll 4.5.5.0 and found `./site watch` doesn't start server because previewServer was not compiled in hakyll by default. 

```
% ./site watch
PREVIEW SERVER
Initialising...

  Creating store...
The preview server is not enabled in the version of Hakyll. To
  Creating provider...
enable it, set the flag to True and recompile Hakyll.
  Running rules...
Alternatively, use an external tool to serve your site directory.
Checking for out-of-date items
Compiling
Success
```

Forcing compile with previewServer flag break hakyll compilation. So what is the right way for previewing my site at http://localhost:8000 now?

**Comment by turboMaCk** [comment]
Hello.
I've ran into this issue and don't know how to neither solve nor debug it. I'm using `hakyll-4.8.3.2`. 

```
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library
```

I've tried (re)install/clean/configure/build multiple times.

I also tried stack install but that also didn't work due to this: https://github.com/jaspervdj/hakyll/issues/475

**Comment by turboMaCk** [comment]
Works after update to 4.9.0.0. Thx @jaspervdj
