### ISSUE TITLE
Please add Hakyll to Stackage

### ISSUE THREAD

**Issue by emchristiansen** [jaspervdj/hakyll#299]
This will address any installation issues and ensure Hakyll plays well with other packages.
See https://github.com/fpco/stackage.

**Comment by pharpend** [comment]
Any progress on this?

**Comment by superfunc** [comment]
Just pinging @jaspervdj to see if he'd consider this. I got tired of dealing with dep. hell, but I'd really like to have Hakyll back.

Thanks.

**Comment by jaspervdj** [comment]
I'll send a pull request to include it.

**Comment by Decoherence** [comment]
:+1:

**Comment by egonSchiele** [comment]
Hakyll is in stackage now, so this issue can be closed.

**Comment by jaspervdj** [comment]
Thanks for the heads up @egonSchiele.
