### ISSUE TITLE
improving cacheble resource

### ISSUE THREAD

**Issue by piyush-kurur** [jaspervdj/hakyll#303]
For css/javascript/font files a standard technique to increase
performance is to set the file name based on the content and make sure
that the webserver sends longer cache times say 1 year or so. To
implement this, one would want to get unique file names for each
identifier.

```haskell
cssRule = match "style/*.css"
            route addContentVersion -- name modulo bike shedding.
			...
```

The route constructor `addContentVersion` is essentially like
setExtension. It picks a content based name and add it to a original
name. i.e it converts foo.ext to foo-version.ext where version is some
thing that depends on the content (say the sha1sum).

We then need to get the actual file name in the templates which I
guess is not difficult.

Does this look like a good idea? I believe the cache management in
Hakyll already does some content based checking to see if some
resource needs recompilation or not in which case we can reuse that
mechanism.

**Comment by 3v0k4** [comment]
I'd love to be able to add the fingerprints to css files as mentioned by the OP. 

Is there any way to make that happen?
