### ISSUE TITLE
Please support random 1.1

### ISSUE THREAD

**Issue by peti** [jaspervdj/hakyll#307]
I believe lifting the restriction in the Cabal file is all there is to it, i.e. hakyll isn't affected by API changes.

**Comment by hdgarrood** [comment]
It seems hakyll allows random 1.1 as of 4.6.0.0: https://github.com/jaspervdj/hakyll/blob/hakyll-4.6.0.0/hakyll.cabal so I think this can be closed.

**Comment by jaspervdj** [comment]
Yes, thanks for bumping!
