### ISSUE TITLE
Test suite does not compile

### ISSUE THREAD

**Issue by snoyberg** [jaspervdj/hakyll#345]
Preprocessing test suite 'hakyll-tests' for hakyll-4.6.8.0...

src/Hakyll/Web/Template/Context.hs:40:18:
    Could not find module ‘Data.Time.Locale.Compat’
    It is a member of the hidden package ‘time-locale-compat-0.1.0.1’.
    Perhaps you need to add ‘time-locale-compat’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
hakyll-4.6.8.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by jaspervdj** [comment]
Thanks for reporting!
