### ISSUE TITLE
Hakyll should let caller decide exit

### ISSUE THREAD

**Issue by edom** [jaspervdj/hakyll#347]
I propose 5baa5f1a559e1e0dd57364c9dc945505c3a86db5 as a better solution to #154 and #156.

Use case: I have this code to show all drafts (posts without 'publish' tag in their metadata):

```haskell
import qualified Control.Monad as Cm
import qualified Data.List as L
import qualified System.Environment as Env

import qualified Control.Concurrent.STM as Stm

import qualified Hakyll as H

listDrafts :: IO ()
listDrafts = do
    v <- Stm.newTVarIO []
    Env.withArgs ["rebuild"] $ H.hakyllWith cnf $ do
        H.match "post/*.md" $ do
            H.compile $ do
                id_ <- H.getUnderlying
                p <- H.getMetadataField id_ "publish"
                let publish = maybe False (const True) p
                Cm.unless publish $ H.unsafeCompiler $ Stm.atomically $ Stm.modifyTVar' v (id_ :)
                H.makeItem ("" :: String)
    -- Note: can't do this if Hakyll exits
    putStrLn $ replicate 32 '-'
    Stm.readTVarIO v >>= mapM_ print . L.sort
    where
        cnf = H.defaultConfiguration
            {
                H.destinationDirectory = "_killme"
                , H.storeDirectory = "_killme/_store"
                , H.tmpDirectory = "_killme/_tmp"
            }
```

**Comment by jaspervdj** [comment]
I also think that's nice but the naming convention used is a bit weird -- I would expect `IO` functions ending with `_` to *ignore* the return value, and here it's exactly opposite.

Perhaps we could just have `hakyllWithExitCode`? I don't think we need `hakyll_` -- people who want to do custom stuff with exit codes should now Haskell well enough to be able to plug in the `defaultConfiguration`. What do you think?

**Comment by edom** [comment]
I agree. Sorry, I didn't think much about the naming. :laughing: 

I followed your suggestion to come up with 04c8764dc7056ae0dad6891c1266ecc45a9843da.

**Comment by jaspervdj** [comment]
Applied, thanks!
