### ISSUE TITLE
Markdown file with `test´ in it results in an error

### ISSUE THREAD

**Issue by beerendlauwers** [jaspervdj/hakyll#353]
A Markdown file with the contents "`test´" (do not include quotes) will result in the following error during building:

```
hGetContents: invalid argument (invalid byte sequence)
```

This is on Windows 7, Stackage LTS 2.13.

**Comment by jaspervdj** [comment]
This is an encoding issue. Hakyll and Pandoc use UTF-8 for both input and output. Are you sure this markdown is encoded as UTF-8?

**Comment by beerendlauwers** [comment]
You're probably right, I can't reproduce this anymore with:
```bash
chcp 65001
site build
```
