### ISSUE TITLE
Cannot install hakyll 4.7.1.0

### ISSUE THREAD

**Issue by ntimeu** [jaspervdj/hakyll#356]
Hi,

I am actually trying to install Hakyll, and at some point in time, after doing
```bash
cabal install hakyll
```

I got an error on pandoc :
```
Configuring pandoc-1.14.1...
Failed to install pandoc-1.14.1
Build log ( /home/cxxwaves/Desktop/.cabal-sandbox/logs/pandoc-1.14.1.log ):
cabal: Error: some packages failed to install:
hakyll-4.7.1.0 depends on pandoc-1.14.1 which failed to install.
pandoc-1.14.1 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
/usr/lib/ghc/unix-2.6.0.1/libHSunix-2.6.0.1.a(execvpe.o): In function
`pPrPr_disableITimers':
(.text+0x300): multiple definition of `pPrPr_disableITimers'
/home/cxxwaves/Desktop/.cabal-sandbox/lib/x86_64-linux-ghc-7.6.3/unix-2.7.1.0/libHSunix-2.7.1.0.a(ghcrts.o):(.text+0x0):
first defined here
collect2: error: ld returned 1 exit status
)
pandoc-citeproc-0.7.2 depends on pandoc-1.14.1 which failed to install.
```

Does anyone has this error/know how to drop this error ? (GHC-7.6.3, cabal-install-1.22.6.0, Debian 8). I am compiling inside a sandbox (without sandbox I got a maximum recursion limit reach).

**Comment by ccressent** [comment]
It looks like pandoc is being linked against unix-2.6 and unix-2.7 at the same time?
I found the following threads about a similar problem:

https://www.reddit.com/r/haskell/comments/3634x2/cabal_is_giving_a_weird_error_when_attempting_to/
https://groups.google.com/forum/#!topic/pandoc-discuss/0r9Hhl730LY

It looks like upgrading to a newer version of GHC and/or purging the cabal packages did the trick for these guys. Is that an option for you?

**Comment by ntimeu** [comment]
Hi ccressent, thanks for the answer.

I purged the cache several times, but nothing happened. I now have compiled GHC 7.10 (lastest release) and installed cabal 1.22, and it works perfectly.

Perhaps GHC 7.10 is able to compile multiple versions of the same package ?

**Comment by ccressent** [comment]
I honestly don't know :)
I'm pretty sure, though, that's it's not an issue with Hakyll per se!

**Comment by ccressent** [comment]
Actually, I've just noticed that error you've reported has been making the Travis-CI build fail for the last 3 months and it's using GHC 7.6.3, just like in your original PR...

**Comment by rolfkleef** [comment]
I had the same problem on Ubuntu 14.04. Installed Haskell using the Ubuntu instructions on https://www.haskell.org/downloads/linux - still didn't work with 7.8.4, but indeed does work with 7.10.2 (and cabal 1.22) for Hakyll 4.7.2.0

**Comment by egonSchiele** [comment]
Same issue here, solved by using stackage instead.

**Comment by haoyun** [comment]
oops same problem here.

**Comment by treeman** [comment]
Ran into the same issue with 7.8.4. Got it to work by rerunning `cabal install cabal-install` which will do a reinstall and then doing `cabal install hakyll` again.

Works without issues in 7.10.2 though.

**Comment by jgm** [comment]
I've made some changes to pandoc's Setup.hs that should solve this probably once and for all (once we have a new release).
