### ISSUE TITLE
SASS relative imports

### ISSUE THREAD

**Issue by ThibaudDauce** [jaspervdj/hakyll#357]
Hi,

I'm trying to compile my Sass files with the standard code sample from the documentation:
```haskell
    match "css/knacss.scss" $ do
        route   $ setExtension "css"
        compile $ getResourceString >>=
            withItemBody (unixFilter "sass" ["-s", "-scss"]) >>=
            return . fmap compressCss
```

And it doesn't work, I receive an error:
```
[ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sass -s -scss -I css gave exit code 65
```

It does work when I run:
```bash
sass --scss css/knacss.scss
```

It doesn't work when I run:
```bash
cat css/knacss.scss | sass -s --scss                                                                                          1 ↵
Error: File to import not found or un
readable: helpers/mixins.
       Load path: /home/thibaud/Code/my-site (DEPRECATED)
        on line 29 of standard input
  Use --trace for backtrace.
```
Because I use imports and I'm running `sass` from the root directory and not the `css` directory.

But it works when I run:
```bash
cat css/knacss.scss | sass -s --scss -I css
```
To add the `css` directory to the imports.

And it doesn't work in Hakyll when I add these parameters (same error as before):
```haskell
    match "css/knacss.scss" $ do
        route   $ setExtension "css"
        compile $ getResourceString >>=
            withItemBody (unixFilter "sass" ["-s", "-scss", "-I", "css"]) >>=
            return . fmap compressCss 
```

What do you think I should do?
It may be an other problem than the imports…

Thanks,
Thibaud

**Comment by ccressent** [comment]
I remember struggling with a similar issue about a year ago. I ended up passing the file names to sass instead of piping in the content of the files; see my relevant commit: https://github.com/ccressent/cressent.org/commit/8c5603453a5f968e600cf3317cd10037e3f45b55

Maybe that will do the trick for you too?

**Comment by ThibaudDauce** [comment]
Thanks, it works perfectly!
