### ISSUE TITLE
Its hard to use template variables in a non-template file that needs Pandoc

### ISSUE THREAD

**Issue by egonSchiele** [jaspervdj/hakyll#359]
Suppose I have an `index.markdown` file that will get compiled to `index.html`. This markdown file uses some template vars: `$title$` for example. Now I compile it like this:

```haskell
compile $ do
    pandocCompiler
    >>= applyAsTemplate indexContext
```

First using pandoc to convert markdown to html, then using `applyAsTemplate` for the template variables in `index.markdown`. The problem is, when Pandoc reads the markdown file, it uses `pandocExtensions` by default (see [this file](https://hackage.haskell.org/package/pandoc-1.11.1/docs/src/Text-Pandoc-Options.html#ReaderOptions)). One of the Pandoc extensions is tex. So it reads in all the template variables as math! So none of the variables get interpolated.

You can solve the problem like this:

```haskell
readerOpts :: ReaderOptions
readerOpts = def { readerExtensions = githubMarkdownExtensions }

compile $ do
    pandocCompilerWith readerOpts def
    >>= applyAsTemplate indexContext
```

But it was non-obvious to me, and this seems like a common use case. Is it worth mentioning in the tutorial? Or having a separate function, like `pandocCompilerVars = pandocCompilerWith readerOpts def` ?

**Comment by jaspervdj** [comment]
Hey @egonSchiele,

Relying on Pandoc to leave `$` characters alone is indeed a bit tricky. The recommended way of doing this is first getting these out of there (by applying your template) and then calling out to Pandoc.

So you would do something like this:

```haskell
compile $ do
    getResourceBody
        >>= applyAsTemplate defaultContext
        >>= renderPandoc
        >>= ...
```

Does that work for you?

**Comment by egonSchiele** [comment]
It does! Thanks!
