### ISSUE TITLE
Can connect to 'site' server when using Docker

### ISSUE THREAD

**Issue by dmp1ce** [jaspervdj/hakyll#363]
If I run './site server' in a Docker container, I cannot connect to the server.

I am able to build using './site build' but './site server' does not work in the container. It works fine if I run on my host.

Here is my Dockerfile which shows how to replicate the issue.

https://github.com/dmp1ce/hakyll_server_docker_test

**Comment by jaspervdj** [comment]
Hakyll simply uses Snap underneath to serve the site.

Does this issue manifest for every Snap server?

**Comment by dmp1ce** [comment]
It looks like Snap works fine in a docker container. https://github.com/dmp1ce/snap_docker_test

I'm not sure why Hakyll wouldn't work inside a container.

**Comment by krsch** [comment]
By default hakyll listens on `127.0.0.1`, therefore docker cannot connect to it. If you run `./site server -h 0.0.0.0` everything should work fine.

**Comment by jaspervdj** [comment]
Right, thanks @krsch. The default should probably be `0.0.0.0` then. Feel free to send a pull request @dmp1ce.

**Comment by jonkri** [comment]
Hi, everyone! I can confirm that hakyll still listens on 127.0.0.1.

**Comment by jaspervdj** [comment]
You can use `./site server -h 0.0.0.0`.
