### ISSUE TITLE
Could not find module ‘Haykill’

### ISSUE THREAD

**Issue by usharf** [jaspervdj/hakyll#370]
Using Nixos (unstable) I can run `hakyll-init` but can't compile or import Hakyll as a module.

```sh
ghc --make -threaded site.hs

site.hs:4:18:
    Could not find module ‘Hakyll’
    Use -v to see a list of the files searched for.
```
```sh
Prelude> import Hakyll

<no location info>:
    Could not find module ‘Hakyll’
    It is not a module in the current program, or in any known package.
Prelude> 
```

**Comment by nagisa** [comment]
This is most likely an issue with nixos or your use of nixos.

**Comment by usharf** [comment]
Ok. Was able to install to user profile with no problem.

**Comment by BernardNotarianni** [comment]
@usharf I have same problem (using unstable too). Could you please describe how you made it working?

**Comment by BernardNotarianni** [comment]
Finally had it working.

I followed the instructions from documentation to [install a compiler with libraries](http://nixos.org/nixpkgs/manual/#how-to-create-a-development-environment):

First, I created the file `~/.nixpkgs/config.nix` to define a nix function to install a Hakyll library reachable by the compiler:

``` nix
{
  packageOverrides = super: let self = super.pkgs; in
  {
    myHaskellEnv = self.haskell.packages.ghc7102.ghcWithPackages
                     (haskellPackages: with haskellPackages; [
                       # libraries
                       hakyll
                       # tools
                       # cabal-install haskintex
                     ]);
  };
}
```
Then I executed the command `nix-env -f "<nixpkgs>" -iA myHaskellEnv`.

Now, I can build the site with the regular `ghc --make -threaded site.hs`

**Comment by usharf** [comment]
@BernardNotarianni  :+1: 

I now have a similar setup where hakyll is installed with related cabal packages. I'm still not 100% sure how or why installing standalone to user env does not work... I guess cabal packages are isolated at some level?

My haskelEnv is 
```nix
    haskellEnv = (haskellPackages.ghcWithPackages cabalPackages).overrideDerivation (drv: {
      name = "haskellEnv";
    });
``` 

and cabal packages are defined with:

```nix
   cabalPackages = hp: with hp; [
     cabal2nix
     cabal-install
     ghc-mod
     hakyll
     hasktags
     hoogle
     hlint
     stylish-haskell
   ];
  };
```


```bash
nix-env -i haskelEnv

GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Hakyll
Prelude Hakyll> 
```
