### ISSUE TITLE
$partial("templates/categories/$category$")$ doesn't expand $category$

### ISSUE THREAD

**Issue by beerendlauwers** [jaspervdj/hakyll#371]
Or, conversely, `$category$` is passed as a literal:

```bash
[ERROR] Hakyll.Core.Compiler.Require.load: templates/categories/$category$ (snapshot _final) was
not found in the cache, the cache might be corrupted or the item you are referring to might not exist
```

**Comment by beerendlauwers** [comment]
I can probably do this with a `functionField`, although it would be a little verbose:

`$partial( append("templates/categories", id(category) )$`

where `id` does the same as `$category$` but inside a `$` quotation, and `append` is a variadic function that appends all the strings it's given.

**Comment by bergus** [comment]
I don't think `id` is even required. A `functionField "append" (const . concat)` should be enough to make `$partial(append("templates/categories/", category))$` work.

**Comment by jaspervdj** [comment]
Yes, the append function by bergus looks like a good solution.
