### ISSUE TITLE
Feature wish: Add a search function (this is a race ;-))

### ISSUE THREAD

**Issue by dertuxmalwieder** [jaspervdj/hakyll#375]
Hi,

(sorry, this one will be longish, but I want to make my points clear…,)

having been in the process of transitioning from WordPress to some static (not just flat-file) blog for years now (I’m *really* lazy), I still haven’t settled to which system to use. Actually, I had found one which I thought would be perfect, then I noticed that the provided solution for searching articles was not working as intended, especially since there was no way to use it without JavaScript. The most important feature of a blog system **is** a good search functionality, followed by a decent comment solution (but that’s a different thing).

So I’m back on track, looking for *the perfect* static blog solution. I already have a list of such systems which failed to work well for me (mostly theming- or feature-related issues), so I loosened my requirements a bit. I don’t even care which programming language is used anymore as long as it *just works* (as in *it provides a good search function*) and it’s a cool one (as in *it’s not JavaScript*).

**Now here’s what I want:**

The *perfect* static blog solution should, while generating the pages, keep some *full-text index* of the posts and provide a search function which could be accessed through the front-end (like the article listing but filtered by contents). In case this is already possible, please tell me how - I actually searched the docs *and* sources but I haven’t found such a functionality.

As I want you to actually consider this - I know - frequent feature wish within the near future, I posted it to several interesting generators’ issue trackers, including yours. I’ll probably use the Static Site Generator which comes up with a sufficient search functionality first.

Thank you in advance.

**Comment by jaspervdj** [comment]
I'm not sure what you mean by "not JavaScript". It's unfeasible to generate a page statically for every string the user will ever search for. It's more practical to generate some blob (or multiple blobs in a trie) and then handle these with some minimal JavaScript.

**Comment by dertuxmalwieder** [comment]
As far I understand the functionality, it would be enough to have a server-side full-text index and a Haskell script to search it, right?

**Comment by lukasepple** [comment]
Nope, since Hakyll (also) generates static files that are uploaded to a dumb http server.

**Comment by dertuxmalwieder** [comment]
Are you following me?

**Comment by lukasepple** [comment]
No, I am following hakyll and coleslaw as projects.

**Comment by dertuxmalwieder** [comment]
Whoa. That was creepy.

Yes, Hakyll generates static files. That does not invalidate the possibility of searching an index.

**Comment by jaspervdj** [comment]
The whole idea of a static site is having no server-side scripts though.

**Comment by dertuxmalwieder** [comment]
That leaves two options:

1. Generate a static full-text index with an existing search server every time the blog is generated.
2. Use [Tipue](http://tipue-search.com) with jQuery.

Right?

**Comment by jaspervdj** [comment]
Right, although you're not limited to Tipue, you could implement you own version in Elm or PureScript if that floats your boat.

**Comment by beerendlauwers** [comment]
I would personally generate a bunch of files containing useful metadata listings about all the content in the site -- essentially a normalized relational database structure, but without the entire database part. In short, it'd be a data source queryable via the browser. The data source is really just another view of the content that also gets regenerated during site compilation, so it's not really a database.

With that in place, you can just do queries against it with your preferred browser-based library.

As an example of the metadata, you could have a `categories.json` file that simply contains a map of each category to its content. The same thing could be done for tags.

**Comment by lukasepple** [comment]
A `sitemap.xml` could do the job, too.

**Comment by dertuxmalwieder** [comment]
A `sitemap.xml` would not contain keywords.

**Comment by beerendlauwers** [comment]
@lukasepple Someone already has a function for that: http://www.rohanjain.in/hakyll-sitemap/
