### ISSUE TITLE
Feature request: let `listField` contexts access their parent item

### ISSUE THREAD

**Issue by bergus** [jaspervdj/hakyll#377]
Hi,
I'm trying to implement a menu that adapts automatically to my folder structure - I'm not generating a blog with a fixed structure (where posts appear in one location), but rather a documentation site with a more-or-less arbitrarily nested structure (for now only two levels).

Basically I'm trying to create a navigation bar like this, put in my default template:
```
<div id="nav_main">
    <ul>
        $for(topnavs)$$if(active)$<li class="active"><strong>$title$</strong></li>
        $else$<li><a href="$url$">$title$</a></li>
        $endif$$endfor$
    </ul>
</div>
```
Then I'd use `loadAll` or so to get a list of items that should be put in the navigation. This list is then fed into a `listField "topnavs"` that goes into the context for the default template. For each of the items, `url` and `title` can be generated as I want.
However, I do have a problem to determine `active`. Is the currently rendered item (on which my default template is applied) part of the directory described by the respective list item?
For that, I'd need to know the currently rendered item in the list item context. However, neither `listField` nor `listFieldWith` allow for that. At first I thought `listFieldWith` would do the trick, before I realized that it only allows me to choose the list depending on the rendered item, which is not sufficient. I'd rather need something like
```hs
listFieldFor :: String -> (Item b -> Compiler (Context a)) -> [Item a] -> Context b
listFieldFor key f xs = field' key $ fmap (\c -> ListField c xs) . f
--               ^^^^                     ^^^^^^^^^^^^^^^^^^^^^^ changed from listFieldWith
```
(though I guess the name is horrible, and maybe we don't need `Compiler` around `Context a`, and maybe the `[Item a]` should be wrapped in one instead)
Unfortunately `field'` is not exported from `Template.Context`, at least the `Context` constructor was so I could copy it, but that was a bit ugly. Maybe you could create a new `listField…` function? (And document them :-))

Or maybe what I'm doing is a totally bad idea™, and I should rather create my menu using `Template.List.applyJoinTemplateList`?

**Comment by beerendlauwers** [comment]
Have a look at `functionField`: it allows you to define a `Context`-level function that takes a bunch of arguments and the current item being rendered. It's very underdocumented, so [I wrote a blog post on it](http://beerendlauwers.be/posts/2015-09-21-hakylls-functionfield.html).

**Comment by bergus** [comment]
@beerendlauwers: thanks, that was what I eventually went with (though I found the `functionField` in Hakyll's source and your blog post via Google myself).

I was not sure how mighty the `functionFields` are and how save they were to use, given that I used a really complex function with it now. Here's my current solution anyway:
Basically I now do have a `pageItem.html` template with only
```
        $if(active)$<li class="active"><strong>$title$</strong></li>$else$<li><a href="$url$">$title$</a></li>
```
in it.
Then I do have multiple `nav_ABC.html` templates, one for each folder, that look like this:
```
---
title: ABC
navdir: pages/abc
mainpage: intro
---
      <ul class="submenu">
        $navPage("intro")$
        $navPage("example")$
        …
      </ul>
```
in here, I use a `functionField` `navPage` that resolves its argument in the `navdir` (read from metadata) to an `Item`, and then reads its metadata (from a non-final snapshot, to avoid circular dependencies) and passes them to the application of the `pageItem.html` template (using a context that also determines the `active` field).
The `nav_*.html` templates are then dynamically included via a field in my `default.html` template, and the right one is chosen through the `navdir` metadata attribute that "activates" the template if the currently rendered item is located in the `navdir`.
This gives me much flexibility, especially about the order of the items in the menu, which are just listed in the `nav_*.html` template. I also have a functionfield that allows me to generate an overview of the navigation menus (using `title` and `mainpage` from the metadata), so that I get a two-level folder navigation. I do not yet support arbitrary nesting, and don't need it (yet?), so I didn't wrote anything for it, though it's certainly doable.
My actual code is even a bit more complicated as I also maintain multiple language versions of each file, with simple suffices in their file names that need to be accounted for (e.g. in choosing the link and title of each item).

----
Back to the actual feature request:
I had headed further down the `listField` route before switching to the above solution, and when I had to implement support for multiple languages, I found that I indeed needed to make the `[Item]` list dynamic (depending on the language of the current item). So I had used
```hs
listFieldOfWith :: String -> (Item b -> Compiler (Context a)) -> (Item b -> Compiler [Item a]) -> Context b
listFieldOfWith key fc fxs = field' key $ (\item -> liftA2 ListField (fc item) (fxs item))
```
at that time. Though in hindsight, probably a
```hs
listField… :: String -> (Item b -> Compiler (Context a, [Item a])) -> Context b
listField… key f = field' key (fmap (uncurry ListField) . f)
```
would have been more clever.

**Comment by beerendlauwers** [comment]
I've used `functionField` a few times in my [hakyll-extra](https://github.com/beerendlauwers/hakyll-extra) repository, see `applyToTemplate` and `translationsToContextFunctionField`.

**Comment by bergus** [comment]
@beerendlauwers: It's a private repo, maybe I can clean my code up a bit and put it online. Hardly going to publish on hackage, though.
I think it's pretty similar to what you have done with translations - load metadata from everywhere and then use it from clever functionfields - except that I use the `Compiler` not the `Rules` monad (fixes dependency tracking? The builtin `Hakyll.Web.Tags` has some crazy `rulesExtraDependencies` / `makePatternDependency` usage that I didn't completely grasp and didn't want to bother with. I need snapshots to avoid dependency cycles though, so it's probably not optimal).
