### ISSUE TITLE
Hakyll does not see $date$ filed

### ISSUE THREAD

**Issue by mrkkrp** [jaspervdj/hakyll#380]
I've been trying to get it work for an hour, somehow it works in example site but not with custom code.

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Monoid ((<>))
import Hakyll

main :: IO ()
main = hakyll $ do

  …

  match "index.md" $ do
    route $ setExtension "html"
    compile $ pandocCompiler
      >>= loadAndApplyTemplate "templates/index.html"   datedContext
      >>= loadAndApplyTemplate "templates/default.html" datedContext
      >>= relativizeUrls

  match "templates/*" $ compile templateCompiler

datedContext :: Context String
datedContext = dateField "date" "%B %e, %Y" <> defaultContext
```

Say, `default.html` just inserts `$body$`. `index.html` looks like this:

```haskell
Blah blah.

Posted on $date$

$body$
```

`index.md` just defines `$title$` and contains a phrase.

Now, when I try to compile the stuff, I get:

```
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated css/bootstrap.min.css
  updated templates/index.html
  [ERROR] Missing field $date$ in context for item index.md
```

How is that possible? I use `datedContext`, which works for example site somehow, but doesn't work for my file `index.md`.

**Comment by mrkkrp** [comment]
It seems like this is sort of special case, I hope other parts of the system are more predictable.

**Comment by jaspervdj** [comment]
Can you try adding a `published` field to `index.md`, as described here: http://jaspervdj.be/hakyll/reference/Hakyll-Web-Template-Context.html#v:dateField

**Comment by mrkkrp** [comment]
Ahhh. Of course everything is OK now. It's just a bit misleading (IMHO) that value of `published` can be extracted from filenames. Somehow I managed to miss last paragraph in docs for `dateField`. Thank you. Closed.
