### ISSUE TITLE
relativizeUrls is not working for inline CSS

### ISSUE THREAD

**Issue by Paulloz** [jaspervdj/hakyll#381]
Hi there.  
I have a template where I'm using some inline CSS and it seems the `relativizeUrls` is not doing anything on that...
```html
<div style="background-image: url(/foo/bar.jpg)"></div>
```

Everything is available in [this repo](https://github.com/paulloz/pauljoannon.com).

**Comment by beerendlauwers** [comment]
Check out `relativizeUrl ` in my repo [hakyll-extra](https://github.com/beerendlauwers/hakyll-extra).

**Comment by jaspervdj** [comment]
Parsing CSS is a bit outside of the scope of Hakyll. It's great that this is available in an external package.
