### ISSUE TITLE
Getting modificationTimeField(With) to return local time not UTC

### ISSUE THREAD

**Issue by larryhynes** [jaspervdj/hakyll#386]
I'm using the following to implement  `$modified$` in templates, specifically for a `sitemap.xml`

```haskell
sitemapModCtx :: Context String
sitemapModCtx =
    modificationTimeField "modified" "%Y-%m-%dT%H:%M:%S%z" `mappend`
    defaultContext
```
And it works, much to my astonishment. :smile: 

I've been trying to see if I can get the resultant time to show my *local* timezone, and not UTC - the `%z` in the above - which should show `+01:00` at the moment, as we're still in Daylight Savings Time, aka Irish Summer Time. So I'm curious to figure out why haskell insists on returning a UTC time string:

```
2015-10-20T20:07:18+0000
```
All my locale environment settings are `en_IE`, so I'm assuming haskell just ignores what I would consider to be the usual `locale` environment. I tried various invocations around stuff like

```haskell
sitemapModCtx :: Context String
sitemapModCtx =
    modificationTimeFieldWith defaultTimeLocale "modified" "%Y-%m-%dT%H:%M:%S%z" `mappend`
    defaultContext
```
combined with `import System.Locale` or `import Data.Time` to no avail, and I can't for the life of me figure out where I might attack this very minor, yet pleasantly irritating, problem next.

I suspect that this is not a hakyll issue *per se* but is more reflective of how haskell does things, and I apologise for cluttering up your issue tracker; if no-one has any insights to share, I'll close this issue promptly.

**Comment by jaspervdj** [comment]
Right. Hakyll was actually not providing an interface to do this, so I've uploaded `hakyll-4.7.4.0` to Hackage which supports this. From that version on, Hakyll now exposes the `getItemModificationTime` function. This allows you get the modification time in UTC, which you can then convert to local time using the functions from `Data.Time`.

Something like this should work:

```haskell
localModifiedTime :: Context a
localModifiedTime = field "mtime" $ \i -> do
    mtime    <- getItemModificationTime (itemIdentifier i)
    timeZone <- unsafeCompiler getCurrentTimeZone
    let localTime = utcToLocalTime timeZone mtime
    return $ formatTime defaultTimeLocale "%H:%M:%S" localTime
```

**Comment by larryhynes** [comment]
Ah, great - thanks Jasper. I tweaked it a little bit by using `utcToZonedTime` instead of `utcToLocalTime`, which allowed me to get the full date format that I was looking for, so it now looks like

```haskell
localModifiedTime :: Context a
localModifiedTime = field "mtime" $ \i -> do
    mtime    <- getItemModificationTime (itemIdentifier i)
    timeZone <- unsafeCompiler getCurrentTimeZone
    let localTime = utcToZonedTime timeZone mtime
    return $ formatTime defaultTimeLocale "%Y-%m-%dT%H:%M:%S%z" localTime
```

combined with

```haskell
sitemapModCtx :: Context String
sitemapModCtx =
    localModifiedTime `mappend`
    defaultContext
```
allows me to use `$mtime$` in my `sitemap.xml` template. Hurrah!

Thanks for your help, and for creating and maintaining such a cool project.
