### ISSUE TITLE
Allow `Pattern` to match absolute filepaths

### ISSUE THREAD

**Issue by seagreen** [jaspervdj/hakyll#387]
The idea is that some users might have content directories they'd like to store somewhere other than inside of their hakyll directory, but still have those files included in the hakyll output.

E.g. I keep hakyll at `/home/seagreen/hakyll`, but I'd like the generated site to include articles from `/home/seagreen/writing/articles/*`

Would this be a beneficial change to Hakyll? If so I might make a PR for it.

**Comment by krsch** [comment]
Why don't you just make a symlink from `/home/seagreen/hakyll/articles` to
`/home/seagree/writing/articles`?

2015-11-02 2:38 GMT+03:00 Ian Jeffries <notifications@github.com>:

**Comment by seagreen** [comment]
@krsch: That's actually what I'm doing right now.

Sometimes it's cleaner not to have a symlink though (e.g. they may contain a lot of data you don't want included in `grep`, you don't want them in version control, etc.) All those issues can be handled with other tweaks of course, but it would be nice to have the freedom to be explicit.

**Comment by seagreen** [comment]
PS: Thanks for the helpful suggestion though, even though it turned out to be what I was already doing:)

**Comment by jaspervdj** [comment]
One thing to note is that `Hakyll` first loads all filenames in the `storeDirectory` given in the configuration, and then uses that list continuously to pattern match. We could extend `storeDirectory` to have it take a *list* of directories instead, but then we need to be a bit careful if a certain filename occurs in more than one directory.

**Comment by seagreen** [comment]
I have a long term question about Hakyll that might be relevant here. Right now Hakyll only accepts files as input. Is this purposeful or incidental?

I could see myself wanting to store site content in Redis/SQLite/Postgres/something else someday. If this could be implemented cleanly, would it be a good thing for Hakyll to support, or is it outside of the project's scope?

The reason I bring it up is because the simplest way I can think of to support other datastores would be a to have something like:

```
data ContentStore =
  { _listContents :: IO [String]
  , _getItem :: String -> IO String
  }
```

And then add a `[ContentStore]` field to `Configuration`. The default for this field would just be a single `ContentStore` that reflects the current behavior exactly -- only check the current directory for content.

The cool thing about this would be that it would support storing content in other directories, as well as more exotic locations like Redis or whatever.

Does that idea make sense?

**Comment by jaspervdj** [comment]
That idea makes sense and I would really like that. In fact, that is the reason `Provider` is a datatype right now. However, coming up with a clean design is probably fairly tricky. I'm closing this issue, feel free to open a new one for the extension.
