### ISSUE TITLE
Get FilePath for an item/identifier in the cache folder (store)

### ISSUE THREAD

**Issue by lippling** [jaspervdj/hakyll#391]
Hello,

I have the following code:

    match "device-images/iPhone-6-Mockup.png" $ do
        -- route not needed, because it is a temporary file
        compile $ getResourceLBS
            >>= withItemBody (unixFilterLBS "convert" ["-", "-virtual-pixel", "transparent", "+distort", "Perspective", "58,215,-221,122 58,1548,233,2403 807,1548,1427,2044 807,215,948,6", "png:-"])

    match "projects/*/images/details/*" $ version "originals" $ do    
        route $ gsubRoute "/details/" $ const "/details/originals/"
        compile withItemBody (unixFilterLBS "convert" ["-", "<IPHONE IMAGE FILE NAME HERE>", ............. "jpg:-"]) image

How can I get the file name within the cache folder (store)? ```getRoute``` does not work, because I don't have a route and I don't want a route because the image is not used in the final output.

**Comment by jaspervdj** [comment]
I think you would typically load the image in the second compiler using `loadBody`?

```haskell
mockup <- loadBody "device-images/iPhone-6-Mockup.png" :: Compiler LB.ByteString
-- Then use mockup ...
```

**Comment by lippling** [comment]
Thanks. Will check that out. I thought `load*` would load the source file and not the destination file.
