### ISSUE TITLE
listField for menu

### ISSUE THREAD

**Issue by Superpat** [jaspervdj/hakyll#393]
I'm confused as to how I should get metadata from my pages to use in a context, I'm trying to build the menu automatically from the url and title fields of the matched pages.

Here is the context I devised:

    menuContext :: String -> Context String
    menuContext lang = 
        listField "menu-items" defaultContext (return pages) <>
        defaultContext
        where pages <- recentFirst =<< loadAll (lang ++ "/*")

I'm 99% sure the error is in the where, but how do I fix it?

**Comment by asayers** [comment]
GHC's output is actually pretty useful here:

```
parse error on input ‘<-’
Perhaps this statement should be within a 'do' block?
```

**Comment by Superpat** [comment]
I'm still quite a novice in Haskell and havent gotten to that point in my reading yet, I'll skip a few chapters to find it out I guess.

**Comment by asayers** [comment]
Good luck! If you need help, remember to stop by #haskell-beginners on freenode.
