### ISSUE TITLE
Preprocessing css and js with gulp

### ISSUE THREAD

**Issue by uglymunky** [jaspervdj/hakyll#396]
Hi, I'm new to Haskell and thought I would start by making a blog with Hakyll.  How could I go about integrating a gulp css/js compilation step?

based off of what I saw [here](https://jaspervdj.be/hakyll/reference/Hakyll-Core-UnixFilter.html) I tried the following for compiling sass files but it didn't work:

```
    match "scss/style.scss" $ do
        route   $ setExtension "css"
        compile $ getResourceString >>=
            withItemBody (unixFilter "gulp" ["sass"])
```

**Comment by jaspervdj** [comment]
Why do you need gulp? Can you not just call sass directly? I'm unfamiliar
with gulp, but I doubt that `gulp sass` works as a unix filter?

**Comment by uglymunky** [comment]
In this case, I'm using gulp to compile es6 javascript code into es5 code and since I'm already using gulp (along with babel and rollup) for that, I figured to also use it for the sass stuff.

**Comment by uglymunky** [comment]
So far, I've got it working by doing the following:

1. remove all css/js processing out of the `site.hs` file
2. run `site build`
3. run `gulp build`

Perhaps there is some way to have `site build` execute `gulp build` so that I don't have to do it as a separate step (I could also write a script for that but thought it would be great if the hakyll build could take care of it for me)

Please excuse me if I'm totally looking at this the wrong way :)

**Comment by beerendlauwers** [comment]
Perhaps have a look at [Shake](http://shakebuild.com/manual) ?

**Comment by jaspervdj** [comment]
You can also do something like:

```haskell
import System.Process (rawSystem)

main = hakyll $ do
    preprocess $ do
        _ <- rawSystem "gulp" ["build"]
        return ()

    -- normal hakyll code
    -- ...
```

**Comment by uglymunky** [comment]
Ah, thanks @jaspervdj, I like that and will give that a shot when I get back to working on it.

Alternatively, I might just wrap all the build commands with [npm scripts](https://medium.com/@housecor/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.ukmh8472c)

**Comment by uglymunky** [comment]
@jaspervdj I'm getting the following error when I use that script:

```
site.hs:12:14: Not in scope: ‘rawSystem’
```

**Comment by jaspervdj** [comment]
Don't forget the import line: `import System.Process (rawSystem)`.

**Comment by uglymunky** [comment]
ugh, my bad.  Thanks.
