### ISSUE TITLE
How to composite two compilers? 

### ISSUE THREAD

**Issue by 0a-** [jaspervdj/hakyll#398]
I am using sassCompiler from `Hakyll.Web.Sass` but the result isn't compressed so I'd like to compile it with `compressCssCompiler` afterwards, I tried

```
match "scss/*" $ do
        route   $ setExtension "css"
        compile compressCssCompiler
        compile sassCompiler
````

but `compressCssCompiler` isn't run at all so I'd like to know what to do in such scenario (I'm still in the midst of learning Haskell so I would really appreciate if anyone can help me with this).

**Comment by jaspervdj** [comment]
This code does not do what you think it does.

```haskell
match "scss/*" $ do
        route   $ setExtension "css"
        compile compressCssCompiler  -- Set the compiler to `compressCssCompiler`
        compile sassCompiler  -- Set the compiler to `sassCompiler`
```

So the second line overwrites the first one. What you want to do is use a combination:

```haskell
match "scss/*" $ do
        route   $ setExtension "css"
        compile $
            sassCompiler >>=
            return . compressCss
```

**Comment by 0a-** [comment]
Oh I see. So I need to make it into a functor first. Thanks!
