### ISSUE TITLE
File encoding errors

### ISSUE THREAD

**Issue by whatsthepoint** [jaspervdj/hakyll#399]
The issue with file encoding errors on non-utf8 locales is already documented in the [FAQ], but it can also be resolved inside the program:
```{.haskell}
import qualified GHC.IO.Encoding as E
main :: IO ()
main = do
  E.setLocaleEncoding E.utf8
  hakyll ...
```
Is there a downside to just making it the Hakyll default?
[FAQ]: http://jaspervdj.be/hakyll/tutorials/faq.html#hgetcontents-invalid-argument-or-commitbuffer-invalid-argument

**Comment by jaspervdj** [comment]
I think it would be a bit annoying/mysterious for people who use some other encoding intentionally. I've added a note in the FAQ though.
