### ISSUE TITLE
Bypassing argument parsing

### ISSUE THREAD

**Issue by halfflat** [jaspervdj/hakyll#400]
As Hakyll.Commands and Hakyll.Core.Runtime are not exported packages, there doesn't seem to be a way to write a main function that bypasses Hakyll's command line parsing (say, to provide a different command line interface.)

My use case is the integration of Hakyll's site building process in an existing make-based environment in a separate build tree. I would like not to have to modify the site.hs source to modify source and destination directories in-place, but instead provide these as command-line parameters.

An alternative to exporting these packages would be to provide functions in Hakyll.Main that split the responsibility of parsing the command-line arguments from invoking the Hakyll commands.

(edit) Rather belatedly it occurs to me one can use withArgs to work-around this issue, though it does lack a certain elegance.

**Comment by jaspervdj** [comment]
I think a solution that splits argument parsing and invoking commands would be the most elegant. This sounds like a good idea to me, it makes Hakyll more library-like.

**Comment by aesadde** [comment]
Hi @halfflat ,

I'd like to help with this feature.

Could you provide a small example of the kind or argument parsing you'd like to do?

**Comment by halfflat** [comment]
Hi!

As a start, I could point you towards the [`site.hs`](https://github.com/BlueBrain/rdmini/blob/master/doc/src/site.hs) file in question. It's used in an out-of-source building Makefile, and the command line args are parsed for destination and cache directories before the appropriate Hakyll command is passed on via `withArgs`.

**Comment by aesadde** [comment]
Thanks!

I'll check it out!
