### ISSUE TITLE
Add ability to redirect, like jekyll 

### ISSUE THREAD

**Issue by fxfactorial** [jaspervdj/hakyll#403]
I just switched to hakyll and am quite pleased with it but I've broken my links now. Can hakyll support redirects the same way that jekyll is able to, posted here https://help.github.com/articles/redirects-on-github-pages/ 

Thanks

**Comment by jaspervdj** [comment]
After having a brief look at how this works in Jekyll, I found this:

> Redirects are performed by serving an HTML file with an HTTP-REFRESH meta tag which points to your destination. No .htaccess file, nginx conf, xml file, or anything else will be generated. It simply creates HTML files.

So I guess you can easily do it with Hakyll, you just need to generate a similar HTML file with such a meta tag.

**Comment by gwern** [comment]
Per [my earlier discussion on the mailing list](https://groups.google.com/d/msg/hakyll/sWc6zxfh-uM/fUpZPsFNDgAJ) I've created some functions to do this. The HTML validates and the redirects appear to be working, so I'd like to upstream it.

[0001-module-Hakyll.Web.Redirect-creates-a-set-of-static-H.patch.txt](https://github.com/jaspervdj/hakyll/files/690521/0001-module-Hakyll.Web.Redirect-creates-a-set-of-static-H.patch.txt)

**Comment by jaspervdj** [comment]
@gwern Thanks for the patch!  I have edited it a bit to use more of Hakyll's existing functionality.  This should make it easier to combine it with things like sitemaps, looking up URLs, and other weird dependencies.  The resulting patch is here: <https://github.com/jaspervdj/hakyll/pull/508>.

It would be good to know if this module still satisfies your needs.  The `createRedirects` function is very similar, so I hope it does.

**Comment by gwern** [comment]
The behavior appears to differ subtly.

Checking it out on my database of broken links, it seems that the broken links must no longer start with '/', so the example in the haddocks is now wrong.

Generating my own links and looking for differences, it seems like I also lose the ability to do redirects from the `.page` suffixed versions of pages. A dry run deletes

    delete: 's3://www.gwern.net/Modafinil'
    delete: 's3://www.gwern.net/docs/1997-utena'
    delete: 's3://www.gwern.net/docs/eva/1997-animeland-may-hideakianno-interview-english'
    delete: 's3://www.gwern.net/docs/eva/2002-notenki-memoirs'
    WARNING: Exiting now because of --dry-run

I assume this has to do with some sort of collision between setting extension-less HTML pages:

             match "**.page" $ do
                 route $ setExtension "" -- cool URLs

and defining these redirects:

     ("Modafinil.page", "/Modafinil"),
     ("docs/1997-utena.page", "/docs/1997-utena"),
     ("docs/2002-notenki-memoirs.page", "/docs/eva/2002-notenki-memoirs"),
     ("docs/eva/1997-animeland-may-hideakianno-interview-english.page", "/docs/eva/1997-animeland-may-hideakianno-interview-english"),
     ("docs/eva/2002-notenki-memoirs.page", "/docs/eva/2002-notenki-memoirs"),

**Comment by jaspervdj** [comment]
@gwern Thanks for the feedback.

Regarding the `/`s, I have made this clear in the Haddocks example now.

Regarding the collision: is this because two items match e.g. `"docs/1997-utena.page"`?  In that case, something like this would work elegantly:

```
version "redirects" $ createRedirects
    [ ("Modafinil.page", "/Modafinil"),
    , ("docs/1997-utena.page", "/docs/1997-utena"),
    , ("docs/2002-notenki-memoirs.page", "/docs/eva/2002-notenki-memoirs"),
    , ("docs/eva/1997-animeland-may-hideakianno-interview-english.page", "/docs/eva/1997-animeland-may-hideakianno-interview-english"),
    , ("docs/eva/2002-notenki-memoirs.page", "/docs/eva/2002-notenki-memoirs"),
    , ...
    ]
```

**Comment by gwern** [comment]
Adding the `version` call seems to fix it as far as the dry-run can tell, thanks. I think that takes care of everything, so if you could push it that'd be great.

**Comment by jaspervdj** [comment]
Right -- it is possible for items to collide in terms of `Identifier` even if the final routes are different.  Many sites use this to "overwrite" earlier rules, e.g. first map convert all pages to HTML but then to something different for pages X and Y.  I reckon there should be a setting in Hakyll that causes collisions to error out instead of overwriting.

I've uploaded Hakyll `4.9.3.0` to Hackage which should fix the problem.
