### ISSUE TITLE
How to create filtered rss feeds

### ISSUE THREAD

**Issue by fxfactorial** [jaspervdj/hakyll#404]
I need to generate a custom rss feed, one that is filtered by tags. Is that something that hakyll does or something that I'm expected to do in site.hs?

**Comment by jaspervdj** [comment]
It's possible to do this in your `site.hs`. For example, here I am creating an RSS feed per tag: <https://github.com/jaspervdj/jaspervdj/blob/master/src/Main.hs#L100-L104>.
