### ISSUE TITLE
Broken reference -> source link

### ISSUE THREAD

**Issue by Geof23** [jaspervdj/hakyll#410]
from 
https://jaspervdj.be/hakyll/reference/Hakyll-Core-File.html
to 
https://jaspervdj.be/hakyll/reference/src/Hakyll-Core-File.html#copyFileCompiler

No bueno (404)

**Comment by jaspervdj** [comment]
Thanks for the heads up. It broke because I didn't have `hscolour` on my new machine.

**Comment by Geof23** [comment]
Thanks Jasper, for everything!
