### ISSUE TITLE
$for template leaves trailing spaces behind

### ISSUE THREAD

**Issue by raindev** [jaspervdj/hakyll#414]
This snipped

```
    $for(posts)$
        <a href="$url$">$title$</a> - $date$
    $endfor$
```

will result in this HTML being generated (`.` denotes trailing spaces)

```
....
        <a href="$url$">$title$</a> - $date$
....
```

This snipped will not result in any trailing spaces to the contrary

```
$for(posts)$
    <a href="$url$">$title$</a> - $date$
$endfor$
```

Use of the template should not be affected by the presence of spaces as they are useful for structuring the template code but not needed in the resulting HTML. Even the whole line with the template could be cut out while generating the result.

**Comment by raindev** [comment]
The same applies to `if` template.

**Comment by jaspervdj** [comment]
It's tricky to decide what to do here. The templates are not only used for rendering HTML (e.g., I also use them render markdown for some sites), which _is_ whitespace-sensitive.

I think one solution would be to have something like in Ruby's ERB, e.g.:

- `$foo$`: Renders the key `foo`
- `$-foo$`: Renders the key `foo` and removes leading whitespace from that line
- `$foo-$`: Avoids the line break after the expression

That way, the user can easily control this.

**Comment by raindev** [comment]
Thanks for the timely reply, Jasper. You're right: current behavior isn't a bug exactly. The feature you have described seems like a reasonable design to implement. The issue could be closed, perhaps.

**Comment by jaspervdj** [comment]
I'll leave it open as reminder to myself (or others) to implement this.

**Comment by smorele** [comment]
I've found some cases with ending "-" like [here](https://github.com/jaspervdj/hakyll/blob/32e34f435c7911f36acdf4a62eec1f56faf0b269/tests/data/strip.html#L22)
Is this functionality implemented ?

**Comment by bergus** [comment]
Looks like this can be closed now.

**Comment by jaspervdj** [comment]
Thanks for the ping @bergus!

@smorele Yes, this functionality is now implemented.
