### ISSUE TITLE
install Hakyll on Windows

### ISSUE THREAD

**Issue by haoyun** [jaspervdj/hakyll#419]
I am trying to install hakyll on Windows. but I got the following error

    [33 of 49] Compiling Hakyll.Preview.Poll ( src\Hakyll\Preview\Poll.hs, dist\build\Hakyll\Preview\Poll.o )
    
    src\Hakyll\Preview\Poll.hs:22:1: Warning:
        The import of `throw' from module `Control.Exception' is redundant
    [34 of 49] Compiling Hakyll.Commands  ( src\Hakyll\Commands.hs, dist\build\Hakyll\Commands.o )
    
    src\Hakyll\Commands.hs:92:5: Not in scope: `catchIOError'
    
    src\Hakyll\Commands.hs:92:19: Not in scope: `void'
    cabal.exe: Error: some packages failed to install:
    hakyll-4.8.0.1 failed during the building phase. The exception was:
    ExitFailure 1

I am using the latest Haskell Platform for Windows 7.10.3 from https://www.haskell.org/platform/.
I've checked that I have `base-4.8.2.0` installed.

I think maybe it's because `System.IO.Error` was not imported. I am really new to Haskell.

**Comment by jaspervdj** [comment]
I've bumped `master` to fix this. Would you be willing to try that out or do you prefer me to make a release?

**Comment by haoyun** [comment]
I cloned it to my computer and the error becomes

    [34 of 49] Compiling Hakyll.Commands  ( src\Hakyll\Commands.hs, dist\build\Hakyll\Commands.o )
    
    src\Hakyll\Commands.hs:40:46:
        Module `Control.Exception' does not export `catchIOError'
    cabal.exe: Error: some packages failed to install:
    hakyll-4.8.0.1 failed during the building phase. The exception was:
    ExitFailure 1


I changed `Control.Exception` to `System.IO.Error`, then it worked.

**Comment by jaspervdj** [comment]
Cool, thanks for testing! I've released this change as `hakyll-4.8.1.0`.
