### ISSUE TITLE
Cannot process metadata files with Chinese filenames

### ISSUE THREAD

**Issue by haoyun** [jaspervdj/hakyll#425]
I am with the latest `Hakyll 4.8.3.0` on `Windows 10` with `cmd` and `chcp 65001`.

If I have the following two files in the `posts/` folder
    
    中文.markdown
    中文.markdown.metadata

then when I build the site, I will get

    Initialising...
      Creating store...
      Creating provider...
      Running rules...
    Checking for out-of-date items
    Compiling
      updated templates/default.html
      updated about.rst
      updated templates/post.html
      updated posts/2015-08-12-spqr.markdown
      updated posts/2015-10-07-rosa-rosa-rosam.markdown
      updated posts/2015-11-28-carpe-diem.markdown
      updated posts/2015-12-07-tu-quoque.markdown
      [ERROR] user error (InvalidYaml (Just (YamlException "Yaml file not found: .\\posts/\20013\25991.markdown.metadata")))
    
In the following two cases, Hakyll runs without errors.

* only  having
```
中文.markdown
```
in `/posts`, that is, without using a separate metadata file.
* having
```
english.markdown
english.markdown.metadata
```
in `/posts`, that is, without using a Chinese Character.

**Comment by jaspervdj** [comment]
Hey @haoyun,

I gave the `yaml` library a quick look and it was passing the filename into the C library. Maybe that was what was causing the issues on Windows (it worked fine on Linux). Anyway, I changed this to read the file in Haskell-land and then pass the contents to the `yaml` C library.

Would you be willing to try the master branch and see if that fixes things?

**Comment by haoyun** [comment]
@jaspervdj,
Thank you very much! That works!
