### ISSUE TITLE
build failure in Hakyll/Core/Metadata.hs

### ISSUE THREAD

**Issue by clumens** [jaspervdj/hakyll#426]
[15 of 49] Compiling Hakyll.Core.Metadata ( src/Hakyll/Core/Metadata.hs, dist/dist-sandbox-f3f5fb11/build/Hakyll/Core/Metadata.o )

src/Hakyll/Core/Metadata.hs:117:40:
    No instance for (Binary
                       scientific-0.3.3.8:Data.Scientific.Scientific)
      arising from a use of ‘put’
    In the second argument of ‘(>>)’, namely ‘put n’
    In the expression: putWord8 3 >> put n
    In a case alternative: Yaml.Number n -> putWord8 3 >> put n
cabal: Error: some packages failed to install:
hakyll-4.8.3.0 failed during the building phase. The exception was:
ExitFailure 1

This is with scientific-0.3.3.8 and binary-0.7.5.0 (old, but that's what comes with ghc and the platform) installed.  I almost certainly have the wrong version of something installed, but perhaps the cabal file should be updated to specify?  I'd be happy to test any patches.

**Comment by jaspervdj** [comment]
I pushed a commit which should fix this. If you can test the master branch, I'm happy to do a release.

**Comment by clumens** [comment]
Works for me, thanks!

**Comment by jaspervdj** [comment]
Fixed in `hakyll-4.8.3.1`.
