### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sakshamsharma** [jaspervdj/hakyll#428]
Found a couple of broken links while browsing through the documentation.
Here are a few:

* The 'find it here' link in [this page](https://github.com/jaspervdj/hakyll/blob/master/web/reference.markdown)

* The link to 'file path documentation' [here](https://jaspervdj.be/hakyll/reference/Hakyll-Core-Identifier.html). It's a system link, and assumes GHC path to be 4.8.2

**Comment by jaspervdj** [comment]
The first one is broken since that page is supposed to be viewed through [the hakyll website](https://jaspervdj.be/hakyll/reference.html). The second one has always been a problem. I'm not sure if it's possible to tell `haddock` to generate links that point to Hackage, or even relative links.

**Comment by sakshamsharma** [comment]
Well I think this is reasonable. Leave this issue open for future reports of broken links, or close as you wish :smile:
