### ISSUE TITLE
Cannot compile Hakyll in a sandbox

### ISSUE THREAD

**Issue by alexDarcy** [jaspervdj/hakyll#434]
Hi, I'm using GHC 8.0.1 and cabal 1.24.0.0. When I try to build a project based on hakyll in a sandbox, I get : 

    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/blog/.cabal-sandbox
    Configuring hakyll-2.4.4...
    Building hakyll-2.4.4...
    Failed to install hakyll-2.4.4
    Build log ( /home/blog.cabal-sandbox/logs/hakyll-2.4.4.log ):
    cabal: Entering directory '/tmp/cabal-tmp-11680/hakyll-2.4.4'
    Configuring hakyll-2.4.4...
    Building hakyll-2.4.4...
    Preprocessing library hakyll-2.4.4...
    [ 1 of 24] Compiling Text.Hakyll.Internal.Template.Template ( src/Text/Hakyll/Internal/Template/Template.hs, dist/dist-sandbox-3c36de1e/build/Text/Hakyll/Internal/Template/Template.o )
    [ 2 of 24] Compiling Paths_hakyll     ( dist/dist-sandbox-3c36de1e/build/autogen/Paths_hakyll.hs, dist/dist-sandbox-3c36de1e/build/Paths_hakyll.o )
    [ 3 of 24] Compiling Text.Hakyll.Internal.FileType ( src/Text/Hakyll/Internal/FileType.hs, dist/dist-sandbox-3c36de1e/build/Text/Hakyll/Internal/FileType.o )
    [ 4 of 24] Compiling Text.Hakyll.Context ( src/Text/Hakyll/Context.hs, dist/dist-sandbox-3c36de1e/build/Text/Hakyll/Context.o )
    [ 5 of 24] Compiling Text.Hakyll.HakyllMonad ( src/Text/Hakyll/HakyllMonad.hs, dist/dist-sandbox-3c36de1e/build/Text/Hakyll/HakyllMonad.o )
    
    src/Text/Hakyll/HakyllMonad.hs:20:21: error:
        Module ‘Text.Pandoc’ does not export ‘ParserState’
    
    src/Text/Hakyll/HakyllMonad.hs:21:1: error:
        Failed to load interface for ‘Text.Hamlet’
        It is a member of the hidden package ‘shakespeare-2.0.8.2’.
        Perhaps you need to add ‘shakespeare’ to the build-depends in your .cabal file.
        Use -v to see a list of the files searched for.
    cabal: Leaving directory '/tmp/cabal-tmp-11680/hakyll-2.4.4'
    cabal: Error: some packages failed to install:
    blog-0.1.0.0 depends on hakyll-2.4.4 which failed to install.
    hakyll-2.4.4 failed during the building phase. The exception was:
    ExitFailure 1

And here is my blog.cabal :

    executable site
      main-is:          site.hs
      build-depends:    base == 4.*
                      , hakyll 
                      , filepath
                      , data-default
      ghc-options:      -threaded
      default-language: Haskell2010

**Comment by crodjer** [comment]
Hakyll is now in `4.x.x.x` series and your project is trying to compile `2.4.4`, so it likely won't build because of unpinned dependencies. If you have an older project, you could try explicitly pining your dependencies.

**Comment by sakshamsharma** [comment]
If you do not have an option to switch to a later GHC (and even if you do have that option), I would highly recommend using stack for this purpose.
```
stack setup
stack install hakyll
cd ~/<blog_folder>
stack build
stack exec site build
```

**Comment by alexDarcy** [comment]
I have been trying to set the dependencies number by hand but could not make it working. However, it worked out of the box with stack. Thanks for the help.
