### ISSUE TITLE
Cannot use "loadAll" to load files unless they have already been matched by a "match" block

### ISSUE THREAD

**Issue by chris-kahn** [jaspervdj/hakyll#436]
Not sure if this is intended behaviour or not. Let's say on my website I have a list of "features" I want to show on an html page. I put each one in a markdown file and now I want to `loadAll` to incorporate them into a page. So I write a section like this...

    create ["features.html"] $ do
        route idRoute
        compile $ do
            features <- recentFirst =<< loadAll "content/features/*"
            let ctx =
                    listField "features" featureCtx (return features) `mappend`
                    defaultContext
            makeItem ""
                >>= loadAndApplyTemplate "templates/features.html" ctx
                >>= loadAndApplyTemplate "templates/default.html" ctx
                >>= relativizeUrls

But it doesn't load anything from my features folder, it doesn't compile any of my markdown files there. Now if I add a second section above for each individual feature:

    match "content/features/*" $ do
        route $ setExtension "html"
        compile $ pandocCompiler
            >>= loadAndApplyTemplate "templates/feature.html"     featureCtx
            >>= relativizeUrls

Magically it loads and compiles all my markdown files, and now everything works perfectly. Am I doing sometihng wrong? Shouldn't `loadAll` be able to load my feature markdown files without needing a separate `match` block? I don't want individual feature html pages, I only want the list page.

**Comment by jaspervdj** [comment]
Hello @chris-kahn,

Yes, this is intentional. `loadAll` can only load "known" items, and handles dependency management that way.  If you do not want individual feature html pages, you can do that by **not** `route`-ing these pages anywhere. I also removed `relativizeUrls`, and I think you can remove the `loadAndApplyTemplate` as well, depending on what is in the `templates/feature.html` file.

```
match "content/features/*" $ do
    compile $ pandocCompiler
        >>= loadAndApplyTemplate "templates/feature.html" featureCtx
```

Hope this helps!

**Comment by chris-kahn** [comment]
Thanks! Yeah that helps.
