### ISSUE TITLE
Load created item

### ISSUE THREAD

**Issue by Superpat** [jaspervdj/hakyll#442]
Not 100% sure how to load a created item, I've created a ``menu.html`` and now I want to load it's body inside ``index.html``

``create ["menu.html"] $ do .... ``

    create ["index.html"] $ do
        route idRoute
        compile $ do
            menu <- loadBody "menu.html"
            ....

Is this even possible?

**Comment by jaspervdj** [comment]
Yes, this is entirely possible.  Are you hitting some sort of error when trying this?

**Comment by Superpat** [comment]
No instance for (binary-0.7.5.0:Data.Binary.Class.Binary
                       (Item String -> Compiler String))
      (maybe you haven't applied enough arguments to a function?)
      arising from a use of ‘loadBody’
    In a stmt of a 'do' block: menu <- loadBody "menu.html"
    In the second argument of ‘($)’, namely
      ‘do { menu <- loadBody "menu.html";
            let indexCtx
                  = field "body" menu `mappend` constField "title" "Hair Town"
                    `mappend` constField "lang" "en"
                    `mappend` defaultContext;
            makeItem ""
            >>= loadAndApplyTemplate "templates/default.html" indexCtx
            >>= relativizeUrls }’
    In a stmt of a 'do' block:
      compile
      $ do { menu <- loadBody "menu.html";
             let indexCtx
                   = field "body" menu `mappend` constField "title" "Hair Town"
                     `mappend` constField "lang" "en"
                     `mappend` defaultContext;
             makeItem ""
             >>= loadAndApplyTemplate "templates/default.html" indexCtx
             >>= relativizeUrls }


I expected errors, but I've been able to fix every one except this one.

**Comment by Superpat** [comment]
Just in case, here is how menu.html is created:

    create ["menu.html"] $ do
                compile $ do
                    sections <- loadAll $ fromList ["en/menu/1-hair.html", "2-sub-menu.html", "en/menu/3-about.html", "en/menu/4-contact.html"]
                    let menuCtx =
                            listField "sections" defaultContext (return sections) `mappend`
                            defaultContext
                    makeItem ""
                        >>= loadAndApplyTemplate "templates/menu.html" menuCtx

**Comment by krsch** [comment]
It seems the error lies in using `field`. Using `constField "body" menu` should solve your problem. To prevent problems like this in the future you might want to add type to the `loadBody` call: `menu <- loadBody "menu.html" :: Compiler String` as soon as you find an incomprehensible error.

**Comment by Superpat** [comment]
Hey that worked! Thanks. 

I had based myself on one of the tutorial pages, but I clearly got mixed up with the types.
