### ISSUE TITLE
Using metadata from created item

### ISSUE THREAD

**Issue by Superpat** [jaspervdj/hakyll#443]
I've encountered an issue trying to load a created file inside another one, in creating a sub menu that is then inserted into a menu, the sub menu does not have the needed metadata for the ``listField`` of the menu. ie: using a ``$for$`` loop in the menu template and querying the sub menu's metadata.

        create ["2-sub-menu.html"] $ do
            compile $ do
                subSections <- loadAll "en/sub-menu/*"
                let subMenuCtx =
                        listField "sub-sections" defaultContext (return subSections) `mappend`
                        constField "title" "Beauty care" `mappend`
                        constField "id" "beauty" `mappend`
                        defaultContext
                makeItem ""
                    >>= loadAndApplyTemplate "templates/sub-menu.html" subMenuCtx

ie:

      <div class="slider">
          <div class="slider-container">
          $for(sections)$
              <section id="$id$">
                  $body$
              </section>
           $endfor$
           </div>
      </div>

The ``sections`` field is this: 

``sections <- loadAll $ fromList ["en/menu/1-hair.html", "2-sub-menu.html", "en/menu/3-about.html", "en/menu/4-contact.html"]``

And my specific error message is this:

``[ERROR] Missing field $id$ in context for item 2-sub-menu.html``

**Comment by jaspervdj** [comment]
You probably want to put `subMenuCtx` as a top-level function and then use that whenever you construct the `listField` for the menu.
