### ISSUE TITLE
Port data/example/templates/default.html to HTML5

### ISSUE THREAD

**Issue by ethagnawl** [jaspervdj/hakyll#444]
Would anyone be opposed to porting the templates/default.html file (generated by `hakyll-init`) to valid HTML5? 

I'd wager that a significant portion of the people using `hakyll-init` are doing that themselves, anyways. The folks who aren't (perhaps because they don't know/care about the difference) should _probably_ be using it, too. So, IMHO it'd be a win for everybody.

**Comment by jaspervdj** [comment]
I think that's a very good idea.  Would you be up for doing this?

**Comment by ethagnawl** [comment]
Sure thing.

**Comment by ethagnawl** [comment]
Addressed in #445.
