### ISSUE TITLE
Why base >= 4.8?

### ISSUE THREAD

**Issue by firegurafiku** [jaspervdj/hakyll#456]
Hi!

I tried to build and install master-branch Hakyll using Haskell Platform from my Fedora 24 (it's, currently, the latest release). But got the following error:

``` text
$ cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hakyll-4.8.3.2 (user goal)
next goal: base (dependency of hakyll-4.8.3.2)
rejecting: base-4.7.0.2/installed-cb2... (conflict: hakyll => base>=4.8 && <5)
rejecting: base-4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0,
4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0,
4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global
constraint requires installed instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

What it was?  

Then I manually edited `hakyll.cabal` and fixed base version to `>= 4.7 && <5`, and everything was built successfully. Why to have such a strict version requirement?

**Comment by LaurentRDC** [comment]
I realize this issue is old, but in general: we can only test so many versions of `base` in continuous integration.

Always happy to review pull requests that expand the range of supported libraries
