### ISSUE TITLE
index.html not rendered when accessing localhost:8000

### ISSUE THREAD

**Issue by mnacamura** [jaspervdj/hakyll#457]
Hi, 

I use the latest version in git repo.

Running `stack exec site watch`, accessing `http://localhost:8000`, then it says "File not found" instead of rendering `http://localhost:8000/index.html`.
How can I make the server render `index.html`? 

## Reproducing procedure:

```bash
> hakyll-init foo
> cd foo
> stack init
> git clone https://github.com/jaspervdj/hakyll.git
```
Edit `stack.yaml` and insert `- 'hakyll'` after `packages:`.
```bash
> stack build
> stack exec site build
> stack exec site watch
```
Access `http://localhost:8000`.

**Comment by jaspervdj** [comment]
This should be fixed now, thanks for reporting!

**Comment by mnacamura** [comment]
Thanks for your quick fix!
