### ISSUE TITLE
Partials don't work

### ISSUE THREAD

**Issue by bergus** [jaspervdj/hakyll#460]
I've tried out the latest version (i.e. 82ba9542e75238f4b69d1a497d429962cdff1e14 + #459) and was running into some strange errors that complained about a missing `$body$` field. After turning on verbose mode, and also patching `Context` `<>` to yield errors from failed compiler tries, I got

>   [ERROR] Hakyll.Core.Compiler.Require.load: templates/….html (snapshot _final) was found in the cache, but does not have the right type: expected [TemplateElement] but got Template; Missing field $body$ in context for item pages/….html

That particular template is included via `$partial(…)$` in one of the templates I was applying to the file, so I wondered what could have changed. In fact, nothing did.
But when I had a closer look at the [code for partials](https://github.com/jaspervdj/hakyll/blob/82ba9542e75238f4b69d1a497d429962cdff1e14/src/Hakyll/Web/Template/Internal.hs#L140-L143), I noticed that they use `applyTemplate'` instead of `applyTemplate`, and that it does indeed expect `[TemplateElement]` as its input. However, all included partial files are typically compiled with the `templateCompiler` that yields `Template`s?!
I changed it to `applyTemplate' (unTemplate tpl') context x` and my project started working again.

OK, simple bug, simple fix, but what baffles me is that this code stems right from d32307aa1cbf6718845eeeb2eb6ba3b1c7661bde where the partial system was introduced. How could this be not detected for so long? Maybe it did not threw runtime errors because `Template` is a `newtype` for `[TemplateElement]`? But even then, why does it throw now?

**Comment by jaspervdj** [comment]
It was probably caused by the big template reorganization I did.  I will fix this and add a test.

**Comment by bergus** [comment]
Still, the reorganisation did not change the types of any of the functions involved here, that's what I am so astonished…
And that `newtype` thing was only a wild guess, can you confirm it might be the reason why it worked for so long? I don't know Haskell internals that well (or, for example, how the cache does distinguish types at all during runtime).

**Comment by jaspervdj** [comment]
Right, let's look at the code in question:

```haskell
applyElem (Partial e) = do
    p    <- applyExpr e >>= getString e
    tpl' <- loadBody (fromFilePath p)
    applyTemplate' tpl' context x
```

The return type of `loadBody` is something like `Typeable a => Compiler a`.  This means that `loadBody` returns anything that is `Typeable` -- either `[TemplateElement]` or `Template`, whatever is requested.

We started requesting `[TemplateElement]` in the git version because of the changes, but we are still storing `Template`.  This is where the error originates.  Fortunately, we can catch these things using [Typeable](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Typeable.html) so the error we got was relatively readable.

**Comment by bergus** [comment]
Ah, right, 43c969f326082d29d8e340ee865414deb87b8ac5 is to blame. I was confused, somehow thinking that the parameter type had been `[TemplateElement]` from the very beginning - `git log` said the function hasn't been touched since then, but only because the type was not in the same line as the function name.

Tests and Data.Typeable ftw!
