### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by bergus** [jaspervdj/hakyll#461]
In #460 and in general before when doing complicated stuff in custom `fields`/`functionField`s I noticed that Hakyll always only reports the error message from `missingField`, and not the actual cause of any mistakes.
I even did resort to `return (error "…") :: Compiler String` at some points to get my error messages out to the user (me), which is a very ugly hack.

A quite useful improvement would be to change the `Monoid` instance of `Context`s to

``` haskell
    mappend (Context f) (Context g) = Context $ apply
      where
        apply k a i = f k a i `catchError` \errf ->
                        g k a i `catchError` \errg -> throwError (errf++errg)
```

so that they report all errors that happened when trying to evaluate a field.

I'm not sure though how many messages this might create if multiple fields are chained and whether that might become too many. If it is not too verbose, one might replace all the `empty` return values from contexts (currently it's equivalent to `throwError []`) with things like "_tried field xy_", "_could not generate route for yz_", "_failed to find field wx in metadata of uv_", "_field vw is false_" etc. The date field already does this when failing to parse. While the message would get possibly a bit long, it gives a good summary of what is available in the particular context.

Also it would be helpful if the `$if(…)$` evaluation could report errors. I understand this is a bit complicated as there is no distinction between "field threw error from computation" and "field does not exist". It would be awesome if "expected errors" (no metadata, wrong field name, false boolfields) could somehow be tagged and suppressed while the rest leads to a failing template compilation. This is a breaking change of course, and I'm not sure about its feasibility. Still, maybe you could output errors from if-conditions to `Logger.debug`.

Another great improvement for error messages would be if they reported the name of the template that failed to get applied. This can however not be done by simply adding some parameters to internal functions (like passing the `identifier` right through in `loadAndApplyTemplate`), but would likely require the addition of a `name` field to the `Template` constructor. Oh wait, `Template` implementation _is_ internal :-)

---

I'd like to hear your thoughts on this and can submit a pull request if you think it's worth it.
Having peeked around in the Hakyll source for some time now, it does seem rather easy; but from what I remember unhelpful error messages were nearly a showstopper when I began using Hakyll and writing fields basically had rendered templates as results…

**Comment by jaspervdj** [comment]
- The `Monoid` instance for `Context` uses the `Alternative` instance for `Compiler`.
- I think the `Alternative` instance already provides these messages.  If not, it should.

Try running with `-v`?  You should see something like:

```
  [DEBUG] Hakyll.Core.Compiler.Internal: Adding dependency: IdentifierDependency tutorials/external-clean-urls-with-hakyll.md
  [DEBUG] Hakyll.Core.Compiler.Internal: Alternative failed: Missing field $isSeries$ in context for item tutorials/external-clean-urls-with-hakyll.md
```

The best way to pass in these messages is using `fail "some msg"`, not `return (error "some msg")`.

**Comment by bergus** [comment]
> I think the  Alternative  instance already provides these messages. If not, it should.

It doesn't. I'll open a PR.

**Comment by LaurentRDC** [comment]
Fixed in https://github.com/jaspervdj/hakyll/pull/722
