### ISSUE TITLE
How to change date format ?

### ISSUE THREAD

**Issue by smorele** [jaspervdj/hakyll#465]
I've read the context.hs file to find how to dates are generated but I do not understand how to set dates in a french format (i.e: day-month-year)
Is it possible for an Haskell beginner to change date format ?

**Comment by samgd** [comment]
[dateField](https://hackage.haskell.org/package/hakyll-4.8.3.2/docs/src/Hakyll-Web-Template-Context.html#dateField) uses [formatTime](https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-Format.html#v:formatTime) internally - formatTime's documentation gives a list of the %-codes.

i.e `dateField "date" "%d-%m-%0Y"` does what you want I think (untested)

**Comment by jaspervdj** [comment]
What @samgd said is correct.  Feel free to re-open this issue if that doesn't work.

**Comment by smorele** [comment]
Well, this is why i thought too but it does nos works after modifying the [site.hs](https://github.com/smorele/haskell-101/blob/master/site.hs) and rebuilding the project. :(

**Comment by samgd** [comment]
@smorele: I've just done `hakyll-init` and then changed ```dateField "date" "%B %e, %Y" `mappend` ``` to ```dateField "date" "%d-%m-%0Y" `mappend` ``` in `site.hs` and the dates change as expected. i.e. `December 7, 2015` to `07-12-2015`

Can you post the error message and a simplified example?

**Comment by smorele** [comment]
Well, you can check on [my website](haskell-101.fr) date is not formated as designed in the [site.hs](https://github.com/smorele/haskell-101/blob/master/site.hs)
and I have no error when I run a build or a rebuild :(

**Comment by samgd** [comment]
The linked `site.hs` has a few errors when building, namely the context in the "sitemap.xml" section and indented `postCtx` definition, but if I fix them and run it locally I see [the dates formatted correctly](https://www.anony.ws/i/2016/09/18/2016-09-18-185153.png). 

Are you sure you're building that version?

**Comment by smorele** [comment]
how do you get that errors on building ?

**Comment by samgd** [comment]
```
$ git clone git@github.com:smorele/haskell-101.git
Cloning into 'haskell-101'...
...
$ cd haskell-101/
$ ls
css docs examples fonts haskell101.cabal images index.html posts README.md robots.txt site.hs stack.yaml templates
$ runghc site.hs build

site.hs:48:17: error:
    parse error (possibly incorrect indentation or mismatched brackets)
$ sed -n '47,50p' site.hs
            let sitemapCtx =
                listField "posts" postCtx (return posts) `mappend`

            makeItem ""
$ exit
```

**Comment by smorele** [comment]
well, I am a newcomer to haskell world and I did not knew that command thanks a lot.

**Comment by thalesmg** [comment]
> Well, this is why i thought too but it does nos work after modifying the [site.hs](https://github.com/smorele/haskell-101/blob/master/site.hs) and rebuilding the project. :(

I was trying Hakyll and stumbled upon this problem. In my case, the problem was that I using `stack exec site {build,watch}` but forgot to rebuild the `site` executable itself, since I changed `site.hs`.

So, for anyone in the future that happens to have problems changing the date format, just do:

```bash
stack build
stack exec site clean
stack exec site watch
# or `stack exec site build`
```

Cheers!
