### ISSUE TITLE
Date in the title

### ISSUE THREAD

**Issue by smorele** [jaspervdj/hakyll#468]
Hi,
I have a tiny problem: My article title contains the date and I don't want to.
I'm a newcomer in Haskell world (and then Hakyll) but [this article title](http://www.haskell-101.fr/posts/2016-08-22-une-introduction-aux-fonctions.html) is non valid, [this one](http://www.haskell-101.fr/posts/2016-08-12-pourquoi-haskell.html) is OK but they are built with [the same way](https://github.com/smorele/haskell-101/tree/master/posts) ... 
An idea ?

**Comment by lubomir** [comment]
Wild guess: the `---` lines in the file with wrong heading have trailing whitespace. Could that be a problem?

**Comment by smorele** [comment]
yes, it was the problem, thanks :)
