### ISSUE TITLE
Tutorial missing a step?

### ISSUE THREAD

**Issue by Istap** [jaspervdj/hakyll#473]
I set up hakyll following this [tutorial](https://jaspervdj.be/hakyll/tutorials/github-pages-tutorial.html). Since I am a complete noob I am not sure if I oversaw something obvious, but I before I was able to run `stack exec myblog clean/build` I had to run `stack build`, which created the `myblog` executable. Without this command, both clean and build failed with "Executable named clean/build not found on path".

**Comment by smorele** [comment]
Is it a question ?
The `stack build` command creates an executable. You can get more informations about stack and [workflow](https://docs.haskellstack.org/en/stable/README/#workflow) on [the official website](https://docs.haskellstack.org).

**Comment by christopheryoung** [comment]
I think he's pointing out that the tutorial should advise people to run `stack build` _before_ they try to run `stack exec myblog clean`. As it's currently written, it's likely to confuse people.

**Comment by mchowning** [comment]
Added a PR to address this: https://github.com/jaspervdj/hakyll/pull/588

**Comment by walambert** [comment]
Hi,
The tutorial is still missing the "stack build" step, it would be quite helpful if the tutorial included that. This page (#473) and #588 show up relatively quickly on a google search, but not always, so including that step on the tutorial page would streamline the hakyll setup process for many (especially beginners like myself). Thanks :)

**Comment by jaspervdj** [comment]
Done, sorry for the delay and thanks for the reminders!
