### ISSUE TITLE
LaTeX instead of markdown for posts

### ISSUE THREAD

**Issue by danmchan** [jaspervdj/hakyll#477]
I've been looking for a static site generator that would take LaTeX instead of markdown as source. Hakyll is really great for this as it mostly works out of the box! 

I have run into an issue though where LaTeX `/title` and `/maketitle` don't seem to generate any HTML after getting converted with Pandoc, while `title:` in markdown will. For example, the Carpe Diem markdown example results in 
```html
<h1>Carpe Diem</h1>
```
but any LaTeX source file with

```latex
\title{Carpe Diem}
\begin{document}
\maketitle
\end{document}
 ```

generates
```html
<h1>2016-10-10-filename-of-post-source</h1>
```
instead. 

According to the Pandoc documentation, by default it generates HTML fragments (when not in standalone mode), which does not include the header and footer. That's consistent with what I see when using Pandoc online to preview a conversion. The [Carpe Diem markdown](https://pandoc.org/try/?text=---%0Atitle%3A+Carpe+Diem%0A---%0A%0AFusce+tortor+quam&from=markdown&to=html) does not generate the title, and neither does [LaTeX](https://pandoc.org/try/?text=%5Ctitle%7BCarpe+Diem%7D%0A%5Cbegin%7Bdocument%7D%0A%5Cmaketitle%0AFusce+tortor+quam%0A%5Cend%7Bdocument%7D&from=latex&to=html).

Is there a way to configure Hakyll/Pandoc to generate the titles from LaTex sources?

**Comment by danmchan** [comment]
I started looking through the docs and I see I didn't have a good understanding of how the title is generated. Perhaps the defaultContext when using LaTeX as source doesn't have the correct title metadata? Will need to dig more.

**Comment by danmchan** [comment]
I found the answer in the Hakyll Google group: https://groups.google.com/forum/#!topic/hakyll/VkIWjsGdCmU

The title metadata isn't extracted from LaTeX and the recommended method is to supply the metadata in a separate file: ```foo.tex.metadata```. If you do this, make sure to change your ```site.hs``` so it doesn't try to process the metadata file as post source, e.g. ```match "posts/*.tex" $ do```.

**Comment by wizzup** [comment]
@danmchan I have the same missing title problem when using `file.tex`

I add file.tex.metadata but still have no tilte. The same code work with `file.md` and `file.rst`

I don't understand how to fix `site.hs`, could you provide minimum complete sample as a [gist](https://gist.github.com/)?
