### ISSUE TITLE
Nested compilers

### ISSUE THREAD

**Issue by sakshamsharma** [jaspervdj/hakyll#489]
I'm trying to make a single archive page containing posts by year. I suppose it should be possible with plain JS as well, but what I'm interested in is doing it via Hakyll.

```
       create ["archive.html"] $ do
         route idRoute
         compile $ do
           years <- buildYears "posts/**"
           let pByY = map postsByYear $ map (\x -> fst x) years

           let archiveCtx =
                 listField "years" postCtx pByY `mappend`
                 constField "title" "Archive"   `mappend`
                 defaultContext

           makeItem ""
             >>= loadAndApplyTemplate "templates/archive.html"      archiveCtx
             >>= loadAndApplyTemplate "templates/with-sidebar.html" archiveCtx
             >>= loadAndApplyTemplate "templates/default.html"      archiveCtx
             >>= relativizeUrls
```

Of course, `pByY` is a `[Compiler (Item String)]` rather than a `Compiler [Item String]`, which I'd have liked.

Can someone suggest a way to get a listField, where each entry stands for an year, and each year's entry contains a list (perhaps plain HTML) of posts that year?

I can sense that I'd need another compile inside the original one, but can't get any further yet.

Update: here's `postsByYear`:
```
postsByYear :: Year -> Compiler [Item String]
postsByYear year = do
  posts <- recentFirst =<< loadAll (fromGlob $ "posts/" ++ year ++ "**")
  return posts
```

`buildYears` here, though not necessary:
```
postsByYear :: Year -> Compiler [Item String]
postsByYear year = do
  posts <- recentFirst =<< loadAll (fromGlob $ "posts/" ++ year ++ "**")
  return posts
```

**Comment by jaspervdj** [comment]
I've done a similar thing on [this website](http://burningwheelstour.ch/events/archive/).  The source code of that website can be found [here](https://github.com/jaspervdj/burningwheelstour.ch).  It might need some adaptation though.

**Comment by sakshamsharma** [comment]
Looks interesting. I'd probably spend a few more hours before I get that to work, so postponing for some other day.
Thanks!
