### ISSUE TITLE
001 => 1.0

### ISSUE THREAD

**Issue by rlpowell** [jaspervdj/hakyll#494]
I'm not sure *how*, but with defaultContext, a file named 001.md ends up producing:

    <h1>1.0</h1>

i.e. titleField seems to turn 001 into 1.0.  That's maybe not great.  :D

**Comment by jaspervdj** [comment]
I can't reproduce this with the latest version.  I think this was fixed in #482.  Which version of Hakyll are you using?

**Comment by rlpowell** [comment]
I also cannot repro.
