### ISSUE TITLE
Check exits, even when called as a library function.

### ISSUE THREAD

**Issue by NorfairKing** [jaspervdj/hakyll#496]
`withArgs ["check"] hakyllWithExitCode` exits before returning.

The problem is on line 54 of `Hakyll.Commands`
https://github.com/jaspervdj/hakyll/blob/master/src/Hakyll/Commands.hs#L54

It would also be nice if you could expose these commands, so that I don't have to use `withArgs` to use them.

**Comment by dunnl** [comment]
`Hakyll.Commands.check` is precisely `Hakyll.Check.check` composed with `exitWith`, which doesn't seem to make sense. I think `Hakyll.Commands` should simply re-export `Hakyll.Check.check` and the `>> ok` should be removed from [this line](https://github.com/jaspervdj/hakyll/blob/ead4d71cdcfbfeb636d9e4bfb66d0ef366f7263f/src/Hakyll/Main.hs#L55).

And I'll second the motion to expose `Hakyll.Commands`

**Comment by jedahu** [comment]
Looks like efa148c095f2c556016aa5789b995d4c10fb6eb7 added `>> ok` back on.
