### ISSUE TITLE
`stack install hakyll` fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by verandaguy** [jaspervdj/hakyll#513]
I'm trying to get Hakyll running on a fresh DigitalOcean box running Ubuntu 16.04. Following the instructions on the Hakyll website, I get to `stack install hakyll`, which fails with:

    Invalid package ID: "array-0.5.1.1 base-4.9.0.0 binary-0.8.3.0 bytestring-0.10.8.1"

I subsequently tried to do this step using `cabal`, which succeeded; however, all subsequent `stack` steps failed with the same error, and had to be replaced with their `cabal` equivalents.

I've confirmed that this issue _does not_ exist _at least_ on `4.8.13-1-ARCH`, however it seems to be present on at least the Ubuntu versions available on DigitalOcean.

I'm unsure if the issue is with Hakyll itself, or if it's one of the dependencies.

**Comment by eunchan** [comment]
What is your default stack resolver? For me, I can install hakyll on nightly and lts-7.14

**Comment by verandaguy** [comment]
I was on `lts-7.16`.

I've tried starting over on another new instance with the same OS, but as I explicitly specify `--resolver=lts-7.14` during `stack install hakyll`, I get

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hakyll-4.9.3.0:
    http-conduit-2.1.11 must match >=2.2 && <2.3 (latest applicable is 2.2.3)

Plan construction failed.
```

**Comment by eunchan** [comment]
Hi Jules,

As the other issue mentioned, to install on LTS-7.x, you need to specify
extra-deps as hakyll-4.9.0.0 . Or, you need to use nightly.

Regards,
E.Kim

**Comment by eunchan** [comment]
Duplicated of #475

**Comment by verandaguy** [comment]
Thanks for the link, Ed!

I'm building Hakyll now based on the instructions in #475. It's a tiny
instance with a big swapfile, so it'll take a little while, but I'll
update the thread when the issue wraps up.

**Comment by verandaguy** [comment]
Great success. Installed Hakyll successfully with:

    stack install hakyll --resolver=lts-5.11 --install-ghc
