### ISSUE TITLE
4.9.4.0 doesn't build without external checker

### ISSUE THREAD

**Issue by magthe** [jaspervdj/hakyll#518]
I had to apply the provided patch to make _hakyll_ build without external checker.

    Index: habs/haskell-hakyll/src/hakyll-4.9.4.0/src/Hakyll/Check.hs
    ===================================================================
    --- habs.orig/haskell-hakyll/src/hakyll-4.9.4.0/src/Hakyll/Check.hs
    +++ habs/haskell-hakyll/src/hakyll-4.9.4.0/src/Hakyll/Check.hs
    @@ -27,10 +27,10 @@ import qualified Text.HTML.TagSoup

    --------------------------------------------------------------------------------
    -#ifdef CHECK_EXTERNAL
    import           Control.Exception            (SomeAsyncException (..),
                                                    SomeException (..), try, throw)
    import           Control.Monad.State          (get, modify, StateT, runStateT)
    +#ifdef CHECK_EXTERNAL
    import           Data.List                    (intercalate)
    import           Data.Typeable                (cast)
    import           Data.Version                 (versionBranch)
    @@ -248,9 +248,6 @@ checkExternalUrl url = do
            showException e = case cast e of
                Just (Http.HttpExceptionRequest _ e') -> show e'
                _ -> head $ words $ show e
    -#else
    -checkExternalUrl url = skip url Nothing
    -#endif

    --------------------------------------------------------------------------------
    @@ -274,6 +271,9 @@ requestExternalUrl url = liftIO $ try $
            ua = fromString $ "hakyll-check/" ++
                  (intercalate "." $ map show $ versionBranch Paths_hakyll.version)

    +#else
    +checkExternalUrl url = skip url Nothing
    +#endif

    --------------------------------------------------------------------------------
    -- | Wraps doesFileExist, also checks for index.html

**Comment by jaspervdj** [comment]
Thanks for reporting!  I've released a fix as `hakyll-4.9.5.0`.
