### ISSUE TITLE
`for` iteration over an array of strings

### ISSUE THREAD

**Issue by anatoliykmetyuk** [jaspervdj/hakyll#527]
I have an array of strings in my metadata:

`keywords: [foo, bar]`

I want to iterate over them:

```
$for(keywords)$
$body$
$sep$
$endfor$
```

Or in a similar way. However, `keywords`, being an array, seems not to be parsed to the context.

**Comment by dunnl** [comment]
`for` iterates over `ListField` which is built with `listField`. The idea is to take a list of sub-items and call a context on them to get the key values, not to iterate over a user-passed list like this.

If you need this to work, you could load the metadata with `getUnderlying >>= getMetadata`, lookup the value of `keywords` from there, parse it yourself, create `Item`s with `makeItem`, and pass that list to `listField`. (Just a thought, not something I've tried).

Perhaps read through this post and see if you can adapt it: https://javran.github.io/posts/2014-03-01-add-tags-to-your-hakyll-blog.html
