### ISSUE TITLE
`title` metadata/field is ignored ...

### ISSUE THREAD

**Issue by johanatan** [jaspervdj/hakyll#535]
... and `constField "title" "Hardcoded Title"` is utilized in the site.hs of the new blog template.

I'm using a `fieldContext` as defined below:

```
fieldContext :: String -> Context a
fieldContext s = field s $ \item -> do
    metadata <- getMetadata (itemIdentifier item)
    return $ fromMaybe ("No " ++ s) $ lookupString s metadata
```

and the usage:
```
fieldContext "title"
```
which seems a bit more normative.

**Comment by dunnl** [comment]
This is already done. Every value in the metadata has a key assigned to it by metadataField, which is part of defaultContext.

-- | Map any field to its metadata value, if present
metadataField :: Context a
metadataField = Context $ \k _ i -> do
    value <- getMetadataField (itemIdentifier i) k
    maybe empty (return . StringField) value
