### ISSUE TITLE
Recursively Deletes All Files with `clean` Command

### ISSUE THREAD

**Issue by wisn** [jaspervdj/hakyll#539]
Suppose we initialize new Hakyll application with `hakyll-init site` command. Then, we modify and add some custom configurations below.
```haskell
-- site.hs
...
main = hakyllWith config $ do
...
config :: Configuration
config = defaultConfiguration
    { destinationDirectory = "."
    , providerDirectory    = "sites"
    }
```

The project directory structures looks like this.
```
.
├── site.cabal
├── site.hs
└── sites
    ├── about.rst
    ├── contact.markdown
    ├── css
    │   └── default.css
    ├── images
    │   └── haskell-logo.png
    ├── index.html
    ├── posts
    │   ├── 2015-08-12-spqr.markdown
    │   ├── 2015-10-07-rosa-rosa-rosam.markdown
    │   ├── 2015-11-28-carpe-diem.markdown
    │   └── 2015-12-07-tu-quoque.markdown
    └── templates
        ├── archive.html
        ├── default.html
        ├── post.html
        └── post-list.html
```

Compile the `site.hs` with `stack ghc site`. Run `build` command with `./site build`. The directory structures will be looks like this.
```
.
├── about.html
├── archive.html
├── _cache
        ...
├── contact.html
├── css
│   └── default.css
├── images
│   └── haskell-logo.png
├── index.html
├── posts
        ...
├── site
├── site.cabal
├── site.hi
├── site.hs
├── site.o
└── sites
        ...
```

Try to preview it with `./site server`. It's works fine.

Now, try to run `./site clean` command.
```
Removing ....
site: .: removeDirectoryRecursive:removeContentsRecursive:removeDirectory: invalid argument (Invalid argument)
```

As you can see, this is happens if the `destinationDirectory` option set to `"."`. I think it would be nice if Hakyll populate all `providerDirectory` files and save it to another file like `.clean.metadata`. Yes, `.clean.metadata` will be used for `clean` command.

**Comment by dunnl** [comment]
What is the use case for cluttering your working directory with your compiled site? The typical use case is to build to a separate directory and e.g. `rsync` it to your webserver.

**Comment by wisn** [comment]
@dunnl I'm try to use Hakyll for my GitHub page. For now, I separated the destination directory and use `deploy` command to copy the generated files to the root directory.

**Comment by dunnl** [comment]
Ah, I see. That does make sense. You have probably read [this tutorial](https://jaspervdj.be/hakyll/tutorials/github-pages-tutorial.html) then, which describes a workflow a bit different than what you are doing. Admittedly it's still not particularly nice, but I think it avoids mixing your code with your published site.

**Comment by wisn** [comment]
@dunnl Actually I'm trying to do this too.

[wisn/xmonad-web#gh-pages](https://github.com/wisn/xmonad-web/)

[wisn/xmonad-web#rebuild-xmonad-web](https://github.com/wisn/xmonad-web/tree/rebuild-xmonad-web)
