### ISSUE TITLE
rulesExtraDependencies Usage

### ISSUE THREAD

**Issue by chances** [jaspervdj/hakyll#547]
Referencing the couple of other `rulesExtraDependencies` issues and [this blog post](https://www.blaenkdenum.com/posts/extra-dependencies-in-hakyll/) I wrote this code to compile Sass:

```haskell
match "assets/scss/**/*.scss" $
    compile getResourceBody

sassDependencies <- makePatternDependency "assets/scss/**/*.scss"
rulesExtraDependencies [sassDependencies] $ match "assets/scss/*.scss" $ do
    route   sassToCssRoute
    let compressCssItem = fmap compressCss
    compile (compressCssItem <$> sassCompiler)
```

Sass compilation functions correctly in a clean site build and rebuild, but not on subsequent builds and when watching when I change one of the `assets/scss/**/*.scss` files. Hakyll picks up the changed sub-directory file, but does not recompile any of the `assets/scss/*.scss` files.

For example, changing `assets/scss/party/join.scss` and running build or with watch running:

```
$ stack exec site build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated assets/scss/party/join.scss
Success
```

However, `assets/scss/party.scss` should also have been updated.

**Comment by dunnl** [comment]
From the documentation [here](https://hackage.haskell.org/package/hakyll-4.9.8.0/docs/Hakyll-Core-Identifier-Pattern.html):

> "**": matches one or more elements of an identifier.

The key word is **one** or more. I would expect `**/*.scss` to match `foo/bar.scss` and `foo/bar/qux.scss` but not `foo.scss`. The blog you linked to uses `scss/**.scss`, so perhaps you will have better luck with that.
