### ISSUE TITLE
`match` seem to not match files with leading period

### ISSUE THREAD

**Issue by changlinli** [jaspervdj/hakyll#560]
Steps to reproduce:

Make a file called `.something` with some content in your current file.

Create `hakyllExample.hs` with the following content.

```haskell
import Hakyll

main :: IO ()
main = hakyll $ do
    match (fromGlob ".something") $ do
        route idRoute
        compile copyFileCompiler
```

Nothing is created in `_site` if you run `runhaskell hakyllExample.hs build`. Using `fromRegex`, escaping the period, and `fromList` all don't seem to work.

Changing `".something"` to `"something"` and changing the filename to `something` makes it work.

Strangely `matches (fromGlob ".something") (fromFilePath ".something")` is `True`.

**Comment by jaspervdj** [comment]
By default, Hakyll ignores all files starting with a `.`.  You can tweak this by changing the configuration.

```haskell
myConfig = defaultConfiguration {ignore = \_ -> False}  -- Do not ignore anything
main = hakyllWith myConfig $ do
    ...
```

**Comment by changlinli** [comment]
Cool thanks!
