### ISSUE TITLE
Perfome IO monad in customRoute function

### ISSUE THREAD

**Issue by waddlaw** [jaspervdj/hakyll#563]
I would like to define `content hash route` function.
I tried that use `customRoute` function, but it doesn't satisfy in this case.

Because, To calculate the content hash must read file content.
I don't know that how to performe monadic function (ex: `readFile`) in `customRoute`.

```haskell
customRoute :: (Identifier -> FilePath) -> Routes
customRoute f = Routes $ const $ \id' -> return (Just (f id'), False)
```

Now, I defined that a bit different `customRoute`;

```haskell
customRoute' :: (Identifier -> IO FilePath) -> Routes
customRoute' m = Routes $ const $ \id' -> do
  v <- m id'
  return (Just v, False)
```

If there is another solution then please teach me.
If that's OK with you that I would like to PR.

**Comment by jaspervdj** [comment]
This question was recently answered on the mailing list: <https://groups.google.com/forum/#!topic/hakyll/zdkQlDsj9lQ>.

**Comment by waddlaw** [comment]
Thanks a lot.
Your approach is very cool. 

I solved this problem.
