### ISSUE TITLE
boolField with (Item a -> Compiler Bool)

### ISSUE THREAD

**Issue by Kritzefitz** [jaspervdj/hakyll#564]
The current `boolField` only accepts a function of type `Item a -> Bool`. In some cases it would be useful to have a version of `boolField` that accepts a function fo type `Item a -> Compiler a`.

**Comment by jaspervdj** [comment]
True, but you can also just use `field` -- look at the definition of `boolField`.

**Comment by Kritzefitz** [comment]
Yes, that's what my current solution looks like. Nonetheless I think this would be a helper worth having in Hakyll.

**Comment by jaspervdj** [comment]
Okay, do you want to send a pull request to add `boolFieldM`?

**Comment by LaurentRDC** [comment]
Fixed in #1044
