### ISSUE TITLE
implicit figures are an unpleasant surprise

### ISSUE THREAD

**Issue by clinty** [jaspervdj/hakyll#568]
Please remove Ext_implicit_figures from the default pandoc options

**Comment by jaspervdj** [comment]
I'm sorry but we can't really do this since: this has been the case since the inception of Hakyll, and many people rely on this behavior in their CSS.

**Comment by clinty** [comment]
Fair enough.

For anyone else who hates this, I'm using

    noImplicitFiguresReaderOptions :: ReaderOptions
    noImplicitFiguresReaderOptions = defaultHakyllReaderOptions {
                                         readerExtensions = S.delete Ext_implicit_figures (readerExtensions def)
                                     }
