### ISSUE TITLE
Extend capture with Regex handling

### ISSUE THREAD

**Issue by alhirzel** [jaspervdj/hakyll#578]
I think `capture` in Pattern.hs should be extended to return the capturing groups within a regex. Specifically, something like the following might work (not tested):

    capture (Regex pat) i = Just groups
      where (_, _, _, groups) = ((toFilePath i) =~ pat) :: (String, String, String, [String])

**Comment by jaspervdj** [comment]
Fixed by #599

**Comment by alhirzel** [comment]
Thank you, and merry Christmas!
