### ISSUE TITLE
Stale Haddock documentation

### ISSUE THREAD

**Issue by mbucc** [jaspervdj/hakyll#592]
Was looking for the documentation on new redirect function, and noticed that version of documentation is not in sync with either the releases page or stackage.

https://jaspervdj.be/hakyll/reference/index.html says hakyll-4.7.5.2
https://jaspervdj.be/hakyll/releases.html says HAKYLL 4.9.6.0 
https://www.stackage.org/lts-9.17/hoogle?q=hakyll says hakyll-4.9.8.0

**Comment by mbucc** [comment]
Note: found it on hackage: http://hackage.haskell.org/package/hakyll-4.9.8.0/docs/Hakyll-Web-Redirect.html

**Comment by Minoru** [comment]
Fixed by #905.
