### ISSUE TITLE
hakyll doesn't build in Stackage Nightly (ghc-8.2)

### ISSUE THREAD

**Issue by juhp** [jaspervdj/hakyll#595]
stackage-curator: 
pandoc-2.0.5 (John MacFarlane <jgm@berkeley.edu> @jgm) is out of bounds for:
- [ ] hakyll-4.9.8.0 (>=1.14 && < 1.20). Jasper Van der Jeugt @jaspervdj. @jaspervdj. Used by: library, test-suite

pandoc-citeproc-0.12.1 (John MacFarlane <jgm@berkeley.edu> @jgm) is out of bounds for:
- [ ] hakyll-4.9.8.0 (>=0.10.5 && < 0.11). Jasper Van der Jeugt @jaspervdj. @jaspervdj. Used by: library, test-suite

process-1.6.1.0 is out of bounds for:
- [ ] hakyll-4.9.8.0 (>=1.0 && < 1.6). Jasper Van der Jeugt @jaspervdj. @jaspervdj. Used by: library, test-suite

time-1.8.0.2 is out of bounds for:
- [ ] hakyll-4.9.8.0 (>=1.4 && < 1.8). Jasper Van der Jeugt @jaspervdj. @jaspervdj. Used by: library, test-suite

**Comment by lwm** [comment]
Opened up https://github.com/fpco/stackage/pull/3125 based on https://github.com/fpco/stackage/issues/3032#issuecomment-352554326.

**Comment by mihaimaruseac** [comment]
Hakyll is now in nightly, I think this can be closed.
