### ISSUE TITLE
Please add support for asciidoc.

### ISSUE THREAD

**Issue by wizzup** [jaspervdj/hakyll#600]
I want to try using [asciidoc](http://asciidoc.org/). I think `pandoc` support it [already](https://pandoc.org/demo/MANUAL.txt) but I have no idea how to pass the option to `pandoc`.  

Out-of-the-box support for `file.asciidoc` and `file.adoc` would be nice.

**Comment by jaspervdj** [comment]
Unfortunately Pandoc only supports AsciiDoc as output format, not as input format.

See: <https://github.com/jgm/pandoc/issues/1456>

**Comment by wizzup** [comment]
I see, thank for info.

**Comment by mherzl** [comment]
FYI a solution for how to get asciidoc working has been described in response to [this](https://stackoverflow.com/questions/54338415/is-it-possible-to-use-asciidoc-with-hakyll) SO question.
