### ISSUE TITLE
hakyll 4.10.0 discard attributes of some html tags

### ISSUE THREAD

**Issue by nodew** [jaspervdj/hakyll#608]
stack resolver: lts-10.4
-----------------------
For example:

```html
<!--test.html-->
<ul>
  <li class="test" data-test="data">test</li>
</ul>
```
will be compile to
```html
<!--test.html-->
<ul>
  <li>test</li>
</ul>
```

**Comment by jaspervdj** [comment]
How are you compiling this?  Does it pass through `pandoc`?

**Comment by nodew** [comment]
@jaspervdj 
there is the demo, https://github.com/nodew/blog/blob/master/pages/test.html, you can clone this repo，and run it at local server, then visit the `http://127.0.0.1:8100/test.html` see the result.

**Comment by jaspervdj** [comment]
You are using `pandocCompiler` for the test page.

This parses the HTML page as a Pandoc document (which may not support every HTML element and attribute) and then render it out as HTML again.

Unless there is a specific reason for doing this, try using `getResourceBody` instead -- that just gives you the body (without the metadata header), untouched.

**Comment by nodew** [comment]
Thanks，I'll try it later.
