### ISSUE TITLE
'stack install hakyll' on Ubuntu fails

### ISSUE THREAD

**Issue by agentydragon** [jaspervdj/hakyll#617]
Hi!
I have a homepage written in Hakyll and I encountered the following error trying to install Hakyll on my new laptop.
I basically don't know anything about Haskell dependency management, so I'm a bit lost - there's a pretty good chance there's just something wrong in my environment, but https://jaspervdj.be/hakyll/tutorials/01-installation.html says `stack install hakyll` should work to install from source...

Any ideas what I'm doing wrong, or ways I could patch this?
I tried installing a couple of older versions (like `stack install hakyll-4.x.y.z`), but all of my attempts failed with similar errors.

Thanks for your help!

```
$ stack install hakyll

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hakyll-4.11.0.0:
    http-conduit-2.3.0 from stack configuration does not match >=2.2 && <2.3 (latest matching version is 2.2.4)
    http-types-0.12.1 from stack configuration does not match >=0.9 && <0.12 (latest matching version is 0.11)
    pandoc-citeproc-0.14.1.5 from stack configuration does not match >=0.13 && <0.14 (latest matching version
                             is 0.13.0.1)
    resourcet-1.2.0 from stack configuration does not match >=1.1 && <1.2 (latest matching version is 1.1.11)
needed since hakyll is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps
    in /home/agentydragon/.stack/global-project/stack.yaml:

- http-conduit-2.2.4
- http-types-0.11
- pandoc-citeproc-0.13.0.1
- resourcet-1.1.11

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * You may also want to try using the 'stack solver' command.

Plan construction failed.
```

**Comment by agentydragon** [comment]
I have tried `rm -rf ~/.ghc ~/.cabal ~/.stack` to try to purge any possibly-broken configuration on my system and a fresh `stack install hakyll`, and got the same error.

**Comment by bradyt** [comment]
Maybe you are using the nightly stackage? Perhaps try `stack install hakyll --resolver lts-10.9`, to use a long term stable stackage.

- https://www.stackage.org/lts-10.9
- https://www.stackage.org/lts-10.9/package/hakyll-4.10.0.0

In general, you might have tried the suggestions in that error message.

**Comment by agentydragon** [comment]
Thanks @bradyt - adding `--resolver lts-10.9` made Hakyll install cleanly.
My problem is solved now, but perhaps the installation instructions on the website should be updated to include some long term stable stackage in the installation line, or maybe mention it in the FAQ. I installed stack using the install procedure in their docs (`curl -sSL https://get.haskellstack.org/ | sh`), so it's possible someone else might fall into the same pit that I did.

**Comment by agentydragon** [comment]
I'm leaving this issue open in case someone wants to follow up on it by adding a note about the `--resolver lts-10.9` solution in Hakyll docs.

**Comment by bradyt** [comment]
@agentydragon , what is the output of 

```
cat ~/.stack/global-project/stack.yaml | grep resolver
```

**Comment by agentydragon** [comment]
`resolver: lts-11.0`

Full file attached: [stack.yaml.txt](https://github.com/jaspervdj/hakyll/files/1809772/stack.yaml.txt)

**Comment by bradyt** [comment]
This may be a rumor, but 11.0 was rushed out. Hakyll is not in it.

- https://www.stackage.org/lts-11.0/hoogle?q=hakyll

**Comment by jaspervdj** [comment]
This is not a rumour, Hakyll is objectively not in 11.0.  I was very swamped with work last month and I've only just started catching up on open source things again.  It will soon be in 11.0 (or you can help me speed up the process by adding PRs).

**Comment by jaspervdj** [comment]
Closing this one since the latest Hakyll should install fine.
