### ISSUE TITLE
Add build flag to compile without Pandoc

### ISSUE THREAD

**Issue by bergus** [jaspervdj/hakyll#619]
I am not using Pandoc in my personal project but plain HTML files. Would it be possible to make Pandoc support optional, i.e. a flag to disable it similar to how `previewServer` does remove the snap server from the build? I would hope that this will cut down the huge dependency tree.

**Comment by jaspervdj** [comment]
Yes, we actually don't rely on Pandoc in too many places, so this should be possible.  It would also help a lot with the licensing issues with Pandoc.

**Comment by bergus** [comment]
There are licensing issues o.O?
OK, if you think it's a good idea I will try to learn how to do this.

**Comment by jaspervdj** [comment]
Thanks again for the implementation!
