### ISSUE TITLE
hakyll dropped from stackage lts-11.0?

### ISSUE THREAD

**Issue by iustin** [jaspervdj/hakyll#624]
Looking at https://www.stackage.org/diff/lts-10.10/lts-11.0, it seems that hakyll has been dropped (along with a large number of other package).

If you already knew, sorry for the noise, otherwise, would be good to have hakyll back. Thanks!

**Comment by bergus** [comment]
Already noticed in #617

**Comment by jaspervdj** [comment]
I've opened an issue to get it into the next `lts-11.x` here: <https://github.com/fpco/lts-haskell/issues/117>.

Unfortunately I cannot add it to the nightlies since `pandoc` is not yet there.

**Comment by iustin** [comment]
@bergus - sorry, I scanned the issues quickly, but I haven't seen mentions about it not being included. Fail to build is different.

@jaspervdj - ah, I didn't know pandoc was also dropped. SGTM, thanks.

**Comment by jaspervdj** [comment]
Hakyll is now in LTS-11.2: https://www.stackage.org/lts-11.2/package/hakyll-4.12.0.1
