### ISSUE TITLE
hGetContents error like described in the FAQ, but the solution does not work.

### ISSUE THREAD

**Issue by jparsert** [jaspervdj/hakyll#671]
When using font awesome, I declared it in the Site.hs but when I build the site i get the following error: 

site: ./fontawesome-free-5.4.1-web/webfonts/fa-brands-400.eot: hGetContents: invalid argument (invalid byte sequence)

after setting LANG and adding the     E.setLocaleEncoding E.utf8 as described in the FAQ(https://jaspervdj.be/hakyll/tutorials/faq.html) it still does not work.

**Comment by jaspervdj** [comment]
I assume the problem here is that `.eot` files are binary, so you can't simply read them as a `String`.  Maybe using `copyFileCompiler` will help?

**Comment by jparsert** [comment]
Fixed
