### ISSUE TITLE
syntax.css outdated

### ISSUE THREAD

**Issue by a-vrma** [jaspervdj/hakyll#675]
The default [`syntax.css`](https://github.com/jaspervdj/hakyll/blob/e2db1b21dde1dd0227670b6d84fab3b57411292e/web/css/syntax.css) seems to be outdated or at least significantly different from the output of pandoc's highlighting.
For reference here is a link to the default pandoc syntax-highlighting output as of version 2.3.1
(I think the theme is called pygments) <https://0x0.st/sIVX.css>

**Comment by jaspervdj** [comment]
Thanks for the heads up, should be fixed!
