### ISSUE TITLE
hakyll not available for stack lts 13.x

### ISSUE THREAD

**Issue by Keruspe** [jaspervdj/hakyll#694]
hakyll doesn't seem to be available for those. Any plans on adding it?

**Comment by jaspervdj** [comment]
Yes, I would like to get it back into Stack but I haven't had time to do that yet.  The last time I tried this there were some issues around Pandoc's dependencies, maybe it just works fine now.  Any help is welcome here :-)

**Comment by Lysxia** [comment]
Things are looking good on the latest LTS and nightly, only hakyll and lrucache were missing, and then it just works.

**Comment by Minoru** [comment]
[Since LTS 16.0 Hakyll is back on Stackage](https://www.stackage.org/package/hakyll/snapshots), so I'm closing this.
