### ISSUE TITLE
`match` doesn't seem to work with subfolders

### ISSUE THREAD

**Issue by Ben-Baert** [jaspervdj/hakyll#701]
I'm having a weird issue where a pattern with multiple folders doesn't seem to work:

`match "/folder/*"` seems to work.

`match "/folder/subfolder/*"` doesn't seem to work.

Is this correct? Is there a way to make this work?

**Comment by Radvendii** [comment]
I have `match "blog/posts/*.md"` in my site.hs, but when i change it to `"/blog/posts/*.md"` it breaks. I think the issue here is the leading `"/"`, not the subfolder. Your first example should also fail to match though.

**Comment by jaspervdj** [comment]
I also think the leading `/` should not be there.  Does that fix the problem?  Feel free to reopen if it doesn't!
