### ISSUE TITLE
dependency tracking control

### ISSUE THREAD

**Issue by gnidorah** [jaspervdj/hakyll#704]
I have a case where when one particular item is modified and added by Hakyll dependency tracking for rebuild, I need to mark some more items for rebuilding too. e.g. some magic `markForRebuild item` function in site.hs

Is it possible to add such feature?

**Comment by gnidorah** [comment]
@jaspervdj I've found `outOfDate` function in `Hakyll.Core.Dependencies` but how could I use it?

**Comment by jaspervdj** [comment]
@gnidorah You can use the following: <https://jaspervdj.be/hakyll/reference/Hakyll-Core-Rules.html#v:rulesExtraDependencies>.

Here is some more information on how to use it: <https://jip.dev/posts/extra-dependencies-in-hakyll/>.

**Comment by gnidorah** [comment]
@jaspervdj Hmmm. The problem with this approach is that I can't generate a list of items for rulesExtraDependencies before I know the item that will be rebuild by Hakyll (I have some items chained in doubly linked list, I need to update adjacent pages if new/old page is added/removed).
