### ISSUE TITLE
Foreign Compilers

### ISSUE THREAD

**Issue by adithyaov** [jaspervdj/hakyll#710]
Hi, I was thinking there should be a `module` called `ForeignCompilers`.

The compilers that Hakyll currently has are basic and one could probably use the power of foreign compilers to compile `sass`, `es6` (maybe even `react`), etc.

I haven't thought of how this would work entirely but it seems possible and with some positive response, I could look into it.

I am a bit skeptical about this as it seems like overkill. I wonder what the community thinks about it.

**Comment by Radvendii** [comment]
Check out https://hackage.haskell.org/package/hakyll-sass for sass compilation.

I'm not sure exactly what you mean by foreign compilers, but you can use `unixFilter` and `unixFilterLBS` for most things. See for example, I made a compiler pandoc filter to embed TiKZ output in blog posts: https://taeer.bar-yam.me/blog/posts/hakyll-tikz/.

Is there anything you were looking for that is outside of that scope? Were you just looking for a place to collect community made compilers?

**Comment by adithyaov** [comment]
@Radvendii By Foreign Compilers, I mean using compilers from other languages. For example, Node JS has many beautiful compilers (for ES6, babel, etc). The idea is to use compilers from other languages with Hakyll. The signature for such functions will be something like `String -> IO String`.

This could be achieved by running some system commands. This is definitely not safe and is **system dependent** (Can only run `python` commands if `python` is installed) but can be used with the user knows what they are doing.

The more I think about it, the more skeptical I get. Maybe this is not a proper place for such a discussion although it played really well in my mind. If you think this is a bit too much feel free to close this issue else we can continue discussing this!

**Comment by Radvendii** [comment]
@adithyaov Yeah, this is exactly what `unixFilter String -> [String] -> String -> Compiler String` does. Take a look at https://www.stackage.org/haddock/lts-12.26/hakyll-4.12.4.0/Hakyll-Core-UnixFilter.html.

The only restriction is that the external program has to act like a pipe. It gets in input, and gives out input on the command line, as opposed to generating a file with the output. For most purposes, you can easily create wrappers around programs which output to a tmp directory and then read the output file back to stdout.

**Comment by adithyaov** [comment]
Oh, That's nice :-). Thank you!
