### ISSUE TITLE
How to serve blog posts under multiple routes?

### ISSUE THREAD

**Issue by chshersh** [jaspervdj/hakyll#713]
I have several blog posts. I want to serve each of them under two routes:

1. Default one, like `/posts/2077-09-26-name-of-the-post.html`
2. A short name like `short-name`.

Is there any way to use multiple routes for the same item?

**Comment by wei2912** [comment]
Are you looking at duplicating the post, or to have the `short-name` redirect to the actual post?

**Comment by chshersh** [comment]
I want to redirect. And I've just found [relevant module](http://hackage.haskell.org/package/hakyll-4.12.5.2/docs/Hakyll-Web-Redirect.html) in `hakyll`. Sorry for bothering!
