### ISSUE TITLE
what is the purpose of `missingField`?

### ISSUE THREAD

**Issue by damiencourousse** [jaspervdj/hakyll#718]
The documentation ([for example here](https://jaspervdj.be/hakyll/reference/Hakyll-Web-Template-Context.html#v:missingField)) does not describe what is the purpose of `missingField`.   

My experience it is usually not helpful for the user since the Monoid instance definition of `Context` is such that `mempty = missingField`.

In other words, are there cases where this function could be needed by a user? or should this function be removed the API?

**Comment by bergus** [comment]
IIRC it's helpful for authors, since it provides a more detailed error message.

**Comment by damiencourousse** [comment]
Context definitions combined with `defaultContext` will implicitly embed `missingField`.

In my experience, even if you don't use `mempty`, `missingField` is still called when applying a template (cf. [here](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Web/Template/Internal.hs#L104)).

So from my understanding, there is no reason for an author to explicitly use `missingField`.  Maybe I am missing something?

My point is that `missingField` should be removed from the API, or the documentation should explicit the cases where it is still useful.

**Comment by vaclavsvejcar** [comment]
@damiencourousse I used `missingField` to define my custom `maybeField`, which takes `Maybe` and if the value is present, then adds it under the provided key into the context:

```haskell
-- | Creates a 'field' for given key from optional value.
maybeField :: String -> Maybe String -> Context a
maybeField key = maybe missingField (constField key)

-- | Creates a 'Context' for main template.
siteCtx :: SiteConfig -> Tags -> Context String
siteCtx config tags =
  tagCloudField "cloud" 60 150 tags
    <> constField "buildTime" formattedTime
    <> maybeField "gaId" maybeGaId
    <> defaultContext
```

and then in template:

```html
$if(gaId)$
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', '$gaId$');
  </script>
$endif$
```

Not sure if this is the best way, but it serves its purpose.

**Comment by damiencourousse** [comment]
@vaclavsvejcar  ```Context``` is a ```Monoid``` instance, so you can for instance write:
 ```haskell
-- | Creates a 'field' for given key from optional value.
maybeField :: String -> Maybe String -> Context a
maybeField key = maybe mempty (constField key)
```

Keeping ```missingField``` may have a purpose, e.g. for newcomers that are not familiar with ```Monoid``` instances.  But the documentation is lacking an explanation about the purpose of this function.  Hence my question.

**Comment by damiencourousse** [comment]
I see in the [latest version of Hakyll](https://hackage.haskell.org/package/hakyll-4.13.0.1/docs/Hakyll-Web-Template-Context.html#v:missingField) that ```missingField``` is now better documented, which also addresses my question.
