### ISSUE TITLE
Using custom HTML in post markdown

### ISSUE THREAD

**Issue by Martinsos** [jaspervdj/hakyll#729]
Hi, thanks for this great library!
I am writing my first post in Hakyll, using default blog generated by Hakyll.
I have .markdown file with markdown in it, but I wanted to have title and subtitle that have special styling. Therefore, I wanted to put some spans around it and similar, but then that HTML was not correctly compiled. I realized that pandocCompiler eats some some of the HTML, because that is how it works, so that is the cause. I solved this by doing modifications in templates/post.html, where I defined html for title and subtitle.
However, what if I wanted to add some custom html in the middle of my markdown post? How would you recommend achieveing this in Hakyll? Thanks!

**Comment by jaspervdj** [comment]
If you wrap things in a `<div>` block that starts in a new paragraph, Pandoc should leave it alone.  For example: https://github.com/jaspervdj/jaspervdj/blame/7a6fb371e2d9993e73c8b6c04cd0b0ba703eec69/posts/2019-02-27-beeraffe.markdown#L54-L56

**Comment by Martinsos** [comment]
Thanks @jaspervdj ! Is this documented somewhere and I missed it? If not, what would be the good place to document this?

**Comment by jaspervdj** [comment]
It's a standard Markdown feature -- it's documented on John Gruber's website [here](https://daringfireball.net/projects/markdown/syntax#html).  Hardened markdown parsers (e.g. the comment box I'm writing this in) don't commonly implement it though, since it becomes an attack vector for XSS...
