### ISSUE TITLE
Expose Parser to support non-hakyll arguments

### ISSUE THREAD

**Issue by jhmcstanton** [jaspervdj/hakyll#751]
It would be convenient if hakyll exposed some of the default parsing internals so library users could piggy back new arguments easily. Today it appears that users can either use the default arguments or add an entirely custom set of options that doesn't share any code with the lib.

For example, I use all the default hakyll options today. I would like to add a few feature flags to my site for dev work on top of these, but the parser throws an error if there are any unknown flags included.

**Comment by jhmcstanton** [comment]
I suggest:
- Expose the  [`optionParser`](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Main.hs#L126), [`commandParser`](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Main.hs#L132`)
- Adding a new function `defaultParserPure :: Config.Configuration -> [String] -> Options` that mimics [`defaultParser`](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Main.hs#L73)

**Comment by jaspervdj** [comment]
@jhmcstanton This sounds good to me.  Would you able to do a PR for this?

**Comment by jhmcstanton** [comment]
Sure! Any other thoughts off the top of your head for this?
