### ISSUE TITLE
Support for GHC 8.8

### ISSUE THREAD

**Issue by vaclavsvejcar** [jaspervdj/hakyll#754]
Hello, is there any plan to add support for GHC 8.8? I guess there will be some incompatibilities in `base`, at least related to changes around [MonadFail](https://wiki.haskell.org/MonadFail_Proposal).

**Comment by vrom911** [comment]
This would be very nice to have!
I have opened the corresponding PR for this support — #757 

Let me know if anything else is required to have this issue resolved.

**Comment by vaclavsvejcar** [comment]
@jaspervdj Any chance to have this merged & released? The PR looks really promising :-)

**Comment by jaspervdj** [comment]
@vaclavsvejcar Released in `v4.13.1.0`
