### ISSUE TITLE
Hakyll.Core.Identifier.fromFilePath prepends absolute paths with two //

### ISSUE THREAD

**Issue by JosephLucas** [jaspervdj/hakyll#791]
Hi,

Thanks for developing Hakyll. It is my first static site builder and it worked well until I started to to use some absolute paths.

Why does
```
fromFilePath "/path == "///path"
```
?

This causes unexpected failures when I subsequently try to match items using `fromRegex`.

I really think it's a bug since
```
toFilePath $ fromFilePath "/path"
```
returns "///path"

**Comment by LaurentRDC** [comment]
I'm on Ubuntu right now, and I get (with Hakyll 4.16.3.0):

```bash
$ cabal repl
ghci> fromFilePath "/path"
/path
```

Today, Hakyll's `fromFilePath` is a thin wrapper around [`System.FilePath.normalize`](https://hackage.haskell.org/package/filepath-1.5.3.0/docs/System-FilePath-Posix.html#v:normalise) from the `filepath` package. Note that the behavior of `normalize` is OS-specific.

Just in case, for the future, I have added a property test to ensure this problem doesn't happen again
