### ISSUE TITLE
403 Forbidden when trying to access a file/directory with a dot at the beginning of their name.

### ISSUE THREAD

**Issue by moeHaibane** [jaspervdj/hakyll#793]
I have the following code in my site.hs:
```    
config :: Configuration
config = defaultConfiguration
        { ignoreFile           = const False
        }
main = hakyllWith config $ do
--
match ".well-known/*" $ do
    route   idRoute
    compile copyFileCompiler
--
```
The `.well-known` directory gets successfully compiled with all of it's contents, but when I try to access it, the web server returns 403. Same goes for any filename that starts with a dot.
```
$ curl -I http://127.0.0.1:8000/.well-known/security.txt
HTTP/1.1 403 Forbidden
Date: Wed, 02 Sep 2020 11:19:05 GMT
Server: Warp/3.3.13
Content-Type: text/plain
```
Any idea what's causing this behavior? How do I fix this?

**Comment by bergus** [comment]
This is most likely a problem with your webserver configuration forbidding public access to dotfiles and -directories, not with Hakyll itself.

**Comment by moeHaibane** [comment]
But as you can see the server is 'Warp/3.3.13', which is the webserver that Hakyll utilizes, and I can't really find any info regarding it's configuration. Nothing else comes into play since it's localhost. And even when using NGINX to serve a website that's not deployed by Hakyll, I can access the dotfiles/dirs just fine.
