### ISSUE TITLE
Require.load not found in cache

### ISSUE THREAD

**Issue by Cjen1** [jaspervdj/hakyll#802]
I'm trying to build [this site](https://github.com/Cjen1/cjen1.github.io/blob/src/Site.hs), and I'm persistantly getting cache errors:

```
[ERROR] Hakyll.Core.Compiler.Require.load: papers/biblio.bib (snapshot _final) was not found in the cache, the cache might be corrupted or the item you are referring to might not exist
```

I think I have just missed something in the documentation, but I can't figure out why this isn't working... 

The relevant code is:

```
papersCompiler = do
  bib <- load "papers/biblio.bib"
  csl <- load "papers/acm_citation_style.csl"
  getResourceBody
    >>= readPandocBiblio defaultHakyllReaderOptions csl bib
    >>= return . writePandoc
```

My understanding is that this should try to find "papers/biblio.bib" in either the cache or the file system, but it doesn't seem to be checking the file system (which I've manually verified that its written correctly etc)?

Is there any file path rewriting going on which could be the issue?

**Comment by Cjen1** [comment]
Checking this further. There is a quickcheck in line: https://github.com/jaspervdj/hakyll/blob/478a2e8590c160d0ca657bfbd8e5c852034f651f/lib/Hakyll/Core/Compiler/Require.hs#L63

This checks the universe for the file, which is populated by the ruleset:
https://github.com/jaspervdj/hakyll/blob/478a2e8590c160d0ca657bfbd8e5c852034f651f/lib/Hakyll/Core/Runtime.hs#L61

Which afaict only includes routes.

Thus in this case there is not a route to the file (bc they should not be in the final website) and hence are not in the universe causing that check to fail.

I've got it to build correctly by adding routes to the files via `match`.

So my question this then becomes a question of how to add a rule without it being in the final website.

**Comment by Minoru** [comment]
> So my question this then becomes a question of how to add a rule without it being in the final website.

I haven't tested this, but I think you just add a `match` without a `route` — just a compiler. That's e.g. how templates are handled.

**Comment by Cjen1** [comment]
Yeah I just worked that out :P. Its all working now, but I'm going to submit a PR with a documentation update to hopefully help the next poor bugger after me :)

**Comment by philderbeast** [comment]
This can also happen if you run `stack exec site watch` from anything but the root directory, putting the `_cache` folder in an unexpected location in the folder tree.

**Comment by ribosomerocker** [comment]
I had this issue with
```hs
match ["templates/web"] $ compile templateCompiler
```
and i needed to change it to
```hs
match ["templates/web/*"] $ compile templateCompiler
```
I think the error definitely needs to be improved here.
