### ISSUE TITLE
Code inclusion not working on initial template

### ISSUE THREAD

**Issue by pcoves** [jaspervdj/hakyll#808]
Hi :wave:

I just created a new `hakyll` template using :

```
hakyll-init foo
cd foo
stack init
stack build
```

Then, I followed along with https://github.com/jaspervdj/hakyll/issues/148#issuecomment-17839336 and added the folowing code to the default `contact.markdown` file :

```
~~~~ {.haskell .numberLines startFrom="100"}
qsort []     = []
qsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++
               qsort (filter (>= x) xs)
~~~~
```

I then built the website with `stack exec site build`.

I expected the `_site/contact.html` to embed the code with line numbers and a buch of colors but it's all black on white with a mono font.

Am I missing something?

Thanks in advance!

> P. 

PS: Running an up-to-date archlinux with an up-to-date `stack`.

**Comment by Minoru** [comment]
Hi! Hakyll doesn't ship a CSS file which is necessary for highlighting, so you have to either copy web/css/syntax.css from this repo, or follow #500 to generate your own (I haven't tried that).

**Comment by pcoves** [comment]
Hey, that's a start!

![2020-11-09-133146_525x83_scrot](https://user-images.githubusercontent.com/33952527/98541778-400a8b80-2290-11eb-9dc2-2c465b40837e.png)

Here is the generated code.

```html
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource haskell numberLines"><code class="sourceCode haskell"><span id="cb1-1"><a href="#cb1-1"></a>qsort []     <span class="ot">=</span> []</span>
<span id="cb1-2"><a href="#cb1-2"></a>qsort (x<span class="op">:</span>xs) <span class="ot">=</span> qsort (<span class="fu">filter</span> (<span class="op">&lt;</span> x) xs) <span class="op">++</span> [x] <span class="op">++</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>               qsort (<span class="fu">filter</span> (<span class="op">&gt;=</span> x) xs)</span></code></pre></div>
```


Hoy does one show the line numbers?

Thanks in advance!

> P.

**Comment by Minoru** [comment]
Hmm, no idea regarding the numbers. I'd either poke around with the browser's Inspector tool (F12 in Firefox) to see what CSS style hides them, or found a Hakyll blog that has them and checked what it does to show them.

**Comment by pcoves** [comment]
Well, I can't find any that show the lines.

Even @jaspervdj does not have such a feature at https://jaspervdj.be/posts/2020-09-17-lazysort.html

Also not present on this post which is all about code inclusion http://blog.tpleyer.de/posts/2019-04-21-external-code-inclusion-with-hakyll.html.

Not sure it's doable in an easy way.
But hey, at least I've colors.

**Comment by Minoru** [comment]
Actually, now that I take another look at the HTML you provided — there are no numbers there, just styles! So perhaps the issue is with Pandoc, or its config?

**Comment by pcoves** [comment]
Right.

I'll have a look at pandoc's issues and open this one back if needs be.

Thanks a lot!

**Comment by pcoves** [comment]
Okay, it's not really a `pandoc` issue per se.

At line 19 of [the css file](https://github.com/jaspervdj/hakyll/blob/master/web/css/syntax.css#L19), if you delete ` left: -1em;` you'll have your clickable line numbers.

I never touched a `css` line before so it's ugly but at least it's here.
