### ISSUE TITLE
Hakyll is not compatible with Pandoc 2.11

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/hakyll#812]
There have been a number of changes in Pandoc, in particular relating to citeproc.  See also #799.

**Comment by Minoru** [comment]
Continuing the discussion we started in https://github.com/jaspervdj/hakyll/pull/799#issuecomment-727621556:

> I’m also not super up to date with the pandoc changes but I think pandoc-citeproc may have been folded into pandoc itself?

That's partially right: the new [`Text.Pandoc.Citeproc.processCitations`](https://hackage.haskell.org/package/pandoc-2.11.1.1/docs/Text-Pandoc-Citeproc.html#v:processCitations) replaces the old [`Text.CSL.Pandoc.processCites'`](https://hackage.haskell.org/package/pandoc-citeproc-0.17.0.2/docs/Text-CSL-Pandoc.html#v:processCites-39-) from pandoc-citeproc, but Hakyll uses a more advanced version, [`processCites`](https://hackage.haskell.org/package/pandoc-citeproc-0.17.0.2/docs/Text-CSL-Pandoc.html#v:processCites). Hakyll also exposes a`Reference` type from pandoc-citeproc, and the definitions for those differ between [pandoc-citeproc](https://hackage.haskell.org/package/pandoc-citeproc-0.17.0.2/docs/Text-CSL-Reference.html#t:Reference) and [citeproc](https://hackage.haskell.org/package/citeproc-0.1.1.1/docs/Citeproc-Types.html#t:Reference).

So we have to replace pandoc-citeproc with citeproc. Overall, it looks doable, without even breaking the *shape* of Hakyll's API. However, the differences in `Reference` forces us to bump Hakyll's major version nonetheless. Is that acceptable?

(I'm *not* nominating myself to fix this — yet; I just feeling out the options.)

**Comment by jaspervdj** [comment]
Yeah, sounds like we need to bump Hakyll's major version as well as the lower bound for Pandoc.  I'm fine with both!
