### ISSUE TITLE
Ability to sort items that do not have 'date' field in their metadata

### ISSUE THREAD

**Issue by lippirk** [jaspervdj/hakyll#814]
My use-case is that I have some pdf items and some markdown items in a list that I would like to sort. Since pdfs don't have metadata, using `recentFirst` or `chronological` doesn't work. I have a workaround: add a new sorting function which will use an item's last modification time as a fallback, if the 'date' metdata field is not available. See https://github.com/jaspervdj/hakyll/pull/813

**Comment by pcoves** [comment]
Does https://jaspervdj.be/hakyll/tutorials/02-basics.html#pages-and-metadata help in your case?

You could use a date to a `pdf` using `path/to/the/file.pdf.metadata`.

**Comment by lippirk** [comment]
That's pretty neat, and would definitely solve my issue - thanks! It's not totally clear from the docs whether you have to do something special, or whether it picks up the metadata automatically, but I'll work that out
