### ISSUE TITLE
Build fails with "can't load framework: Cocoa (not found)" on macOS Big Sur

### ISSUE THREAD

**Issue by vaclavsvejcar** [jaspervdj/hakyll#821]
Hello,

I'm not sure if this is related to Hakyll, some of its dependencies or GHC, but I'm unable to build Hakyll (`4.13.4.0`) on macOS Big Sur due to the following error:

```
hakyll     > [48 of 53] Compiling Hakyll.Web.Feed
hakyll     > <command line>: can't load framework: Cocoa (not found)
Progress 1/3

--  While building package hakyll-4.13.4.0 (scroll up to its section to see the error) using:
      /Users/vaclav/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

Do you have any clue what could be the issue?

**EDIT:** It seems to be an GHC + macOS 11 issue - https://gitlab.haskell.org/ghc/ghc/-/issues/18446

**Comment by Minoru** [comment]
Hi! :) Looks like you resolved this yourself: it's going to be fixed in GHC 9.0.1. So Hakyll's unrelated after all, right?

**Comment by vaclavsvejcar** [comment]
Yep, closing this for now.

**Comment by c4dr01d** [comment]
Sorry for re-open this issue, I'm building hakyll using GHC 8.10.1 and Cabal 3.2.0.0, got same error

**Comment by Minoru** [comment]
@mlitux The problem is with GHC, not Hakyll. Your compiler is too old, please upgrade to [at least 8.10.3](https://gitlab.haskell.org/ghc/ghc/-/issues/18446#note_317741).

**Comment by mlitux** [comment]
@Minoru I just found a [workaround](https://github.com/yairchu/macos11-haskell-workaround), it worked.
