### ISSUE TITLE
github-pages-tutorial: recent changes in Github Pages make things much easier than described in the tutorial

### ISSUE THREAD

**Issue by thma** [jaspervdj/hakyll#822]
The Tutorial does not reflect the current version of Github pages, which make integration of Hakyll with GH pages much easier.

I've explained the details here: https://thma.github.io/LambdaBlog/posts/2020-11-15-using-hakyll-with-github-pages.html

if you are interested I can create a pull request with an update to the github-pages-tutorial.

**Comment by Minoru** [comment]
I'd merge such a PR! By the way, you probably want to update the .gitignore file and replace "_site" with "docs" there; or am I missing something?

(On a side note: can you add an Atom or RSS feed to your blog? [Hakyll makes it easy to generate one](https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html)).

**Comment by thma** [comment]
Hi Minoru, 

docs is not in .gitignore by intention. The GH Pages deployment works directly from the docs folder in the master branch.
I'll add the Feeds to by blog and will prepare a PR.
