### ISSUE TITLE
relativizeUrl is overly greedy

### ISSUE THREAD

**Issue by ag-eitilt** [jaspervdj/hakyll#831]
I want to add an external link to `https://pronoun.is/they/.../themself`, while in the same document making use of the `relativizeUrl` feature.  Unfortunately, that compiler reads the three-dot sequence as a two-dot "to parent folder" instruction for some reason---the final document winds up containing a link to `https://pronoun.is/themself` which doesn't actually point anywhere.  I'm not quite sure where that (prefix pattern match?) is occurring, <strike>but it might be possible to work around it by changing the `isPrefixOf` at [Hakyll.Web.Html.RelativizeUrls line 51](https://github.com/jaspervdj/hakyll/blob/f3881821328fae8cba848627f1caf2086121c903/lib/Hakyll/Web/Html/RelativizeUrls.hs#L51) to use [Hakyll.Web.Html.isExternal](https://github.com/jaspervdj/hakyll/blob/e9a8139152b166eae75083259fc3e824675de6fb/lib/Hakyll/Web/Html.hs#L151) instead</strike> (that won't actually help, since the first `isPrefixOf` in the line already filters out anything specifying the protocol).

**Comment by Minoru** [comment]
Hi! I failed to reproduce this with Hakyll 4.13.4.0 (with Stackage LTS 16.21). I added `https://pronoun.is/they/.../them` to a template *and* to a Markdown file (two different ways — `[text](link]` and `[text][anchor] + [anchor]: link`), and all of those had the triple-dot thingy preserved. Can you post a minimal reproducible example somewhere? I suspect there might be something else that is interfering here.

**Comment by ag-eitilt** [comment]
...I somehow had that copied into my file incorrectly.  When the path says to go up a directory, of course the final link will go up a directory.  Sorry!
