### ISSUE TITLE
Hakyll no longer present in Stackage LTS 17.x

### ISSUE THREAD

**Issue by vaclavsvejcar** [jaspervdj/hakyll#832]
Hello,

it looks that _Hakyll_ is not present in [LTS-17.x](https://www.stackage.org/lts), I guess it might be related to Pandoc, which is missing as well for some reason. Anyway, it would be great to have it back 🙂

**Comment by vaclavsvejcar** [comment]
Just FYI Pandoc is [back in LTS](https://www.stackage.org/lts-17.5/package/pandoc-2.11.4).

**Comment by Minoru** [comment]
4.14.0.0 is out now, let's see how fast it'll make its way into Stackage. If I understand correctly, it'll be in Nightly in a few days, and then it'll appear in the next minor release of LTS-17.

**Comment by Minoru** [comment]
I was wrong, Hakyll is still disabled: https://github.com/commercialhaskell/stackage/blob/1d818cad147f5d97f7f4be301ac5bb036a45b2ab/build-constraints.yaml#L824 But I just submitted [a PR to re-enable it](https://github.com/commercialhaskell/stackage/pull/5933), and once it's merged, everything should go as I described above :)

**Comment by Minoru** [comment]
My PR just got merged. Keep an eye out for Hakyll in Stackage Nightly now :)

**Comment by Minoru** [comment]
…but the tests [will be skipped](https://github.com/commercialhaskell/stackage/issues/5795#issuecomment-799522388) because Hakyll 4.14.0.0 doesn't support tasty 1.4. Our next release will include https://github.com/jaspervdj/hakyll/pull/838 which fixed that.

**Comment by Minoru** [comment]
A-a-and we're out of Stackage again: https://github.com/commercialhaskell/stackage/pull/5933#issuecomment-799612398

**Comment by tbelaire** [comment]
Can I help?  I can't run my blog update as is.  Solving the stackage issue seems to be the fastest way forward.

**Comment by Minoru** [comment]
@tbelaire Sure! We're waiting for Pandoc to support time 1.11; if you can submit a PR adding that, it'll be great. Once a new Pandoc release is out, we should double-check that Hakyll is buildable with all the versions mentioned in the aforementioned Stackage comment (bytestring 0.11 might be a problem), and then cut a new Hakyll release, and then submit a PR to Stackage re-enabling Hakyll.

**Comment by HenryDashwood** [comment]
Any updates on when we might see Hakyll back on Stackage? Are you still waiting on Pandoc?

**Comment by Minoru** [comment]
@HenryDashwood No update. It looks like Pandoc still requires `time < 1.10` even on its master branch, and I don't see any outstanding PRs fixing that, so we remain blocked on that. There might be more blockers which we aren't aware of because the solver stumbles on Pandoc first.

**Comment by HenryDashwood** [comment]
Ah fair enough. Thanks for the update!

**Comment by Minoru** [comment]
Once #853 is merged, the only remaining blocker will be pandoc-types, which currently doesn't allow bytestring 0.11.

**Comment by fedeinthemix** [comment]
LTS Stackage is now at 18.6 which does include 'pandoc' and 'pandoc-types'. The latter depends on 'bytestring' and works with the included version which is 0.10.12.0

https://www.stackage.org/lts-18.6/package/pandoc-types-1.22

I guess PR jgm/pandoc-types#92 should no longer be a showstopper and #853 seems merged. Would be great if we could make some progress in solving this issue.

**Comment by Minoru** [comment]
Thanks for the ping @fedeinthemix! I just released Hakyll 4.14.1.0 and submitted [a PR to re-enable it in Stackage](https://github.com/commercialhaskell/stackage/pull/6183). The bytestring-0.11 problem means we could get booted anytime though.

**Comment by Minoru** [comment]
My PR is merged. Hakyll should appear in the next Stackage Nightly today or tomorrow (I think), and from there it'll get into LTS 18.9 (I guess).

**Comment by fedeinthemix** [comment]
Thanks!

**Comment by Minoru** [comment]
We're in nightly-2021-09-06 and newer. My guess about LTS 18.9 was wrong: it's released, but we aren't in it. My new guess is that we'll be added to LTS 19 (whenever that comes out).

**Comment by Minoru** [comment]
Hakyll 4.15.1.1 is part of [LTS 19.0](https://www.stackage.org/lts-19.0) now :tada:
