### ISSUE TITLE
https://jaspervdj.be/hakyll/tutorials/01-installation.html has typos?

### ISSUE THREAD

**Issue by Revilotom** [jaspervdj/hakyll#847]
I think it should be
```
site build
```
```
site watch
```
instead of 
```
my-site build
```
```
my-site watch
```

<img width="731" alt="スクリーンショット 2021-05-25 7 50 43" src="https://user-images.githubusercontent.com/19348723/119416124-f23a0a00-bd2d-11eb-8d1b-3befe27f6485.png">

**Comment by Minoru** [comment]
Hi! Sorry for the delay replying.

Yes, these are typos. I'll fix them in a PR momentarily. If you find any more typos or mistakes, don't hesitate to submit a PR yourself ;)

**Comment by Minoru** [comment]
I don't know when the fix will reach the site though. I'm not the one deploying it, and the owner of this repo doesn't do it often. I guess it'll be done on the next Hakyll release.

**Comment by Revilotom** [comment]
Thank you!
Next time Ill try and make a PR myself
