### ISSUE TITLE
`stack install hakyll` runs out of memory when compiling pandoc 

### ISSUE THREAD

**Issue by dlqs** [jaspervdj/hakyll#856]
I am on a modern Archlinux laptop with 8GB RAM with easily 6GB free when `stack install`ing, and I'm rather surprised even that is not enough RAM. Might I suggest adding a warning about this OOM issue in the [install](https://jaspervdj.be/hakyll/tutorials/01-installation.html) page, or moving upward the suggestion for distro packages.

**Comment by Minoru** [comment]
I'm sorry to hear that it bit you, but won't it be better to fix Pandoc itself? Surely you don't expect us to keep track of how much memory each package takes to compile with each GHC release on each OS?
