### ISSUE TITLE
Small fix in github pages tutorial

### ISSUE THREAD

**Issue by alexandroid000** [jaspervdj/hakyll#860]
Hi,

Redoing my website (hakyll + github pages) and noticed that in section "Modify site.hs", if I follow the guide exactly, the suggested template blog will not compile. The issue appears to be the first `do` in `main` in this code block:

```
config :: Configuration
config = defaultConfiguration
  { destinationDirectory = "docs"
  }

main :: IO ()
main = do
  hakyllWith config $ do
  ...
```

When I remove the first `do`, everything compiles fine.

Cheers!
Alli

**Comment by Minoru** [comment]
Hi, sorry for the slow response! Thank you for the report. You could just submit this as a pull request, but now I'm going to steal your thunder by doing it myself :P
