### ISSUE TITLE
Question regarding duplicating field values

### ISSUE THREAD

**Issue by recursion-ninja** [jaspervdj/hakyll#893]
Suppose I have a field `"SubTitle"` stored in the context originating from the metadata fields in an input file. I would like to dynamically create a second field `"description"` with the same value as `"SubTitle"`, as the presence of this field is expected by another Hakyll function.

I tried the following:

```
descriptionField :: Context a                                                                                       
descriptionField = field "description" $ \i ->                                                                      
    getMetadata (itemIdentifier i) >>= 
    pure . fromMaybe empty . lookupString "SubTitle"
```

However, this seems to always "fail," returning the `empty` value, which is not the desired behavior when the `"SubTitle"` field exists. How can I go about achieving this functionality?

**Comment by Minoru** [comment]
I tried this code on my site to turn `title` into `titleCopy`, and it works for me. I'm building against Stackage LTS 16.21, so Hakyll 4.13.4.0.

Are you sure you are composing the contexts in the correct order? If something to the left of `descriptionField` defines the field of the same name, it will "overwrite" what you've defined here.

**Comment by recursion-ninja** [comment]
The above code does work. There was a misspelling in one off the two string labels. The unavoidable woes of Hakyll being a "stringly typed" interpreter.
