### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by throwaway1037** [jaspervdj/hakyll#920]
Is every file in the project licensed under the `LICENSE` file, such as the articles and tutorials, or just the code?

If it does not apply to everything, please may the webpages be released under a [libre](https://freedomdefined.org) license?

In any case, it would be best to add a license notice to the footer of each page so people can easily tell what the license is.

**Comment by Minoru** [comment]
AIUI, everything is under the MIT license, but it's up to @jaspervdj to decide. I'd personally prefer a Creative Commons license for the tutorials, but so many people edited them by now that I wouldn't bother with re-licensing at this point.

**Comment by jaspervdj** [comment]
I also think Creative Commons may make more sense for the documentation, but I'm unsure if we should go through relicensing unless there's a practical use case where the MIT license is currently holding us back.  Did you have something in mind @throwaway1037?

**Comment by throwaway1037** [comment]
As long as it's libre, I don't mind what the the license is, although I'd recommend strong copyleft in most cases, and as @Minoru said, for articles, a libre CC license is preferable.
The reason I asked for clarification is because Expat is an uncommon choice for an article license, although it's libre nonetheless, and since there were no footers on the webpages I wondered if maybe the Expat license applied only to the code and not every file in the project, including the articles.

As for whether it's worth upgrading the license, if it's faesible then it would be worth upgrading to CC-BY-SA-4.0-Int-or-later because it's both common and copyleft.

In any case, it would be best to include a footer at the bottom of each page so it's clear what the license is.

I'd also like to thank all contributors for writing Hakyll and all the excellent articles!
Sometimes a tutorial series is much more valuable than documentation, especially as a jumping-off point.

**Comment by Minoru** [comment]
Looks like we have a consensus, so I added a mention of BSD3 license to the footer: #922. I'll leave it to @jaspervdj to merge.
