### ISSUE TITLE
.numberLines produces no output in the first column

### ISSUE THREAD

**Issue by emacstheviking** [jaspervdj/hakyll#930]
I also have pandoc installed via brew,
posts|master⚡ ⇒ pandoc -v
pandoc 2.17.1.1
And I am also running hakyll (installed via stack)..

This source input: note that /triple-back-quote/ means '```', I couldn't figure it out in the editor!
```
/triple-back-quote/{.numberLines}
aio.m:043: Unknown format string in call to `io.format'/4.
aio.m:043: Unknown format values in call to `io.format'/4.
aio.m:045: Unknown format string in call to `io.format'/4.
aio.m:045: Unknown format values in call to `io.format'/4.
aio.m:049: Unknown format string in call to `io.format'/4.
aio.m:049: Unknown format values in call to `io.format'/4.
aio.m:052: Unknown format string in call to `string.format'/3.
aio.m:052: Unknown format values in call to `string.format'/3.
/triple back-quote/
```
produces this output
```
<pre class="[sourceCode numberSource numberLines]()"><code class="[sourceCode]()"><span id="[cb1-1]()"><a href="[#cb1-1](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-1)"></a>aio.m:043: Unknown format string in call to `io.format'/4.</span>
<span id="[cb1-2]()"><a href="[#cb1-2](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-2)"></a>aio.m:043: Unknown format values in call to `io.format'/4.</span>
<span id="[cb1-3]()"><a href="[#cb1-3](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-3)"></a>aio.m:045: Unknown format string in call to `io.format'/4.</span>
<span id="[cb1-4]()"><a href="[#cb1-4](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-4)"></a>aio.m:045: Unknown format values in call to `io.format'/4.</span>
<span id="[cb1-5]()"><a href="[#cb1-5](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-5)"></a>aio.m:049: Unknown format string in call to `io.format'/4.</span>
<span id="[cb1-6]()"><a href="[#cb1-6](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-6)"></a>aio.m:049: Unknown format values in call to `io.format'/4.</span>
<span id="[cb1-7]()"><a href="[#cb1-7](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-7)"></a>aio.m:052: Unknown format string in call to `string.format'/3.</span>
<span id="[cb1-8]()"><a href="[#cb1-8](view-source:http://localhost:8000/posts/2022-03-03-mercury-and-nano-a-plugin.html#cb1-8)"></a>aio.m:052: Unknown format values in call to `string.format'/3.</span></code></pre>
```
-- stack information --

posts|master⚡ ⇒ stack upgrade --force-download
Current Stack version: 2.7.5, available download version: 2.7.5
Forcing binary upgrade
Querying for archive location for platform: osx-x86_64-static
Downloading from: https://github.com/commercialhaskell/stack/releases/download/v2.7.5/stack-2.7.5-osx-x86_64.tar.gz
Download complete, testing executable
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4

Warning: Installation path /Users/sean/.local/bin
         not found on the PATH environment variable.
New stack executable available at /Users/sean/.local/bin/stack
Also copying stack executable to /usr/local/Cellar/haskell-stack/2.7.5/bin/stack
Stack executable copied successfully!

posts|master⚡ ⇒ stack --version               
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4

**Comment by Minoru** [comment]
The numbers are added by CSS. If you put your document into a file called _input.md_ and run `pandoc --standalone -f markdown -t html5 input.md`, you'll see some `numberSource` styles at the beginning of the document. For my site, I just copied those styles into my own CSS file, and included that into the site.

**Comment by emacstheviking** [comment]
You sir, @Minoru  are a freaking genius! You have no idea how long I've wanted to fix my blog... happy days and thanks, that closes this ticket in exceptional time!
