### ISSUE TITLE
`tagsFieldWith` requires an custom render link

### ISSUE THREAD

**Issue by jeongoon** [jaspervdj/hakyll#932]
I'm trying to generate 'tags' context from 'keywords' meta data field. however
when I use `buildTagsWith`, it was easy, on the other hand, `tagsFieldWith` requires a custom render link function.
which is actually implemented in https://github.com/jaspervdj/hakyll/blob/3f25fd7d1f7bfef4b726796cf1a109f5fc201b5e/lib/Hakyll/Web/Tags.hs#L333

I could copy and paste and add some more library in my *.cabal,

 I'm just curious, Is there any reason this is not exported by default?
IMHO, It would be much easier if `Tags.hs` offer default renderer for it.

**Comment by Minoru** [comment]
I think it's just an omission. Will be fixed by #933. Thanks for catching this ^_^

**Comment by jeongoon** [comment]
Okay. Thank you for your time.
Ill fix my site.hs after that 😁

**Comment by Minoru** [comment]
I don't want to make a release just to get this out, so you'll have to wait a bit. Or see if you can add Hakyll as a Git dependency ;)

**Comment by jeongoon** [comment]
No problem. :+1: maybe I'll try git dependency for now.
