### ISSUE TITLE
Minor Tutorial Issue

### ISSUE THREAD

**Issue by collin-kemper** [jaspervdj/hakyll#944]
When following the tutorial at https://jaspervdj.be/hakyll/tutorials/01-installation.html using stack, manually creating the `stack.yaml` file resulted in `stack build` failing. However, using the command `stack init` to generate the `stack.yaml` worked. Unless there is some compelling reason not to use stack init, I would recommend replacing the

> Now, change into `my-site` directory and create a file `stack.yaml` here with the following content:
> 
> ```
>resolver: lts-14.16  # Adapt this as needed
>packages:
>  - .
>extra-deps:
>  - hakyll-4.13.0.1  # Or a later version you installed
> ```

With something like:

> Now, change into `my-site` directory and run `stack init` to create the `stack.yaml` file.

I hope this helps.

**Comment by Minoru** [comment]
Good idea, thanks! I applied it in https://github.com/jaspervdj/hakyll/commit/37c65d9d01f0030e79aaf478ac2a30f6069bcba4.
