### ISSUE TITLE
Resource busy when creating multiple versions from one file

### ISSUE THREAD

**Issue by rqy2002** [jaspervdj/hakyll#972]
I has bug #903 again. Using hakyll 4.15.1.1, I get
```
[ERROR] _cache\1358274680180442700 for Hakyll.Core.Resource.Provider.MetadataCache/posts\2022-10-30-test.md/metadata: Store.set: resource busy (file is locked)
```
every time I change the content of `2022-10-30-test.md` and run `stack run -- build`.
But the bug does'nt appear when I rebuild all pages. Maybe it's since that the time between generating different versions are longer in this case ?
It doesn't depend on whether I use "-threaded" or not -- I get the same bug in both situation.

This bug occurs when I want to produce two version of a file, one page and one raw, as in [the tutorial](https://jaspervdj.be/hakyll/tutorials/06-versions.html).

This is part of my `site.hs`:

```haskell
  match "posts/*" $ version "raw" $ do
    route idRoute
    compile getResourceBody

  match "posts/*.md" $ do
    route $ setExtension "html"
    compile $ pandocCompiler'
      >>= loadAndApplyTemplate "templates/post.html" postCtx
      >>= loadAndApplyTemplate "templates/default.html" postCtx
      -- >>= relativizeUrls
```
(where `pandocCompiler'` is pandoc with some configuration).
I don't modify other parts in default `site.hs`.
If I remove the raw version, then the bug doesn't occur.

**Comment by Minoru** [comment]
Sorry for the long wait! The fix for #903 was made *after* 4.15.1.1, so that release is buggy. I just cut a new one, 4.16.0.0, which does include a fix. Please upgrade to that and if the bug persists, comment on #903 again so we can re-open it.
