### ISSUE TITLE
RFC: Styling with CirrusCSS

### ISSUE THREAD

**Issue by ocramz** [jaspervdj/hakyll#994]
Hi there! 

I've had a straightforward experience integrating CirrusCSS (https://cirrus-ui.netlify.app/getting-started/setup ) with Hakyll

1) add `cirrus.min.css` to `css/` (the file is contained in each release. This can be vendored in courtesy of the MIT license : https://github.com/Spiderpig86/Cirrus/blob/master/LICENSE )

Modify header of `templates/default.html` : 

2) add responsive viewport : `<meta name="viewport" content="width=device-width, initial-scale=1">`
3) add CSS import : 
```html
        <!-- Cirrus CSS -->
        <link rel="stylesheet" type="text/css" href="/css/cirrus.min.css" />
```
4) add fonts (optional I think):
```html
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
```
5) style `templates/*.html` to taste

I think a modern look that doesn't require selling one's soul to a CSS minifier framework gizmo is quite desirable in 2023.

WDYT?

**Comment by Minoru** [comment]
Dunno; IMHO the Hakyll site looks pretty sleek as it is.

We might indeed add the responsive viewport to improve how the site looks on mobile, but I wonder what CirrusCSS itself would give us? (Keeping in mind that there is no plans to rework the site in any way; add we do these days is add more content.)

**Comment by ocramz** [comment]
No, I meant the template used by the blog generator, so all generated pages
will use responsive css and so on.

**Comment by jaspervdj** [comment]
@ocramz just to be super clear, we are talking about the template website generated by `hakyll-init`?

I agree that we should include `<meta name="viewport" content="width=device-width, initial-scale=1">` and make some minor changes to the CSS so it looks good on mobile.

I strongly disagree with using Google Fonts.

I also somewhat disagree with using CirrusCSS.  People have suggested using Bootstrap, Tailwind and others.  These can be a big help, but I think they're a bit "flavor of the year".  Furthermore, I think code generation isn't ideal, so the less code (and dependencies) we generate, the better.

I'm actually interested to take a look myself to see if we can accomplish something okay without Cirrus -- if that's not possible, I'm happy to change my stance on this.

**Comment by ocramz** [comment]
@jaspervdj I do agree that UI frameworks are a dime a dozen a year. I can't claim exhaustive knowledge in this area but I did try a few and Cirrus struck me as both dead simple to install and use and good looking. It doesn't require any JS and it's statically bundled (as opposed to both Tailwind and Bootstrap), which is why I proposed it here.
